// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using YoutubeAPI.Models.Trending;
//
//    var trendingModel = TrendingModel.FromJson(jsonString);

namespace YoutubeAPI.Models.Trending
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TrendingModel
    {
        [JsonProperty("contents")]
        public Contents Contents { get; set; }
    }

    public partial class Contents
    {
        [JsonProperty("twoColumnBrowseResultsRenderer")]
        public TwoColumnBrowseResultsRenderer TwoColumnBrowseResultsRenderer { get; set; }
    }

    public partial class TwoColumnBrowseResultsRenderer
    {
        [JsonProperty("tabs")]
        public List<Tab> Tabs { get; set; }
    }

    public partial class Tab
    {
        [JsonProperty("tabRenderer")]
        public TabRenderer TabRenderer { get; set; }
    }

    public partial class TabRenderer
    {
        [JsonProperty("selected")]
        public bool Selected { get; set; }

        [JsonProperty("content")]
        public TabRendererContent Content { get; set; }

        [JsonProperty("tabIdentifier")]
        public string TabIdentifier { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class TabRendererContent
    {
        [JsonProperty("sectionListRenderer")]
        public SectionListRenderer SectionListRenderer { get; set; }
    }

    public partial class SectionListRenderer
    {
        [JsonProperty("contents")]
        public List<SectionListRendererContent> Contents { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("header")]
        public Header Header { get; set; }

        [JsonProperty("targetId")]
        public string TargetId { get; set; }
    }

    public partial class SectionListRendererContent
    {
        [JsonProperty("itemSectionRenderer")]
        public ItemSectionRenderer ItemSectionRenderer { get; set; }
    }

    public partial class ItemSectionRenderer
    {
        [JsonProperty("contents")]
        public List<ItemSectionRendererContent> Contents { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class ItemSectionRendererContent
    {
        [JsonProperty("shelfRenderer")]
        public ShelfRenderer ShelfRenderer { get; set; }
    }

    public partial class ShelfRenderer
    {
        [JsonProperty("content")]
        public ShelfRendererContent Content { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class ShelfRendererContent
    {
        [JsonProperty("expandedShelfContentsRenderer")]
        public ExpandedShelfContentsRenderer ExpandedShelfContentsRenderer { get; set; }
    }

    public partial class ExpandedShelfContentsRenderer
    {
        [JsonProperty("items")]
        public List<ExpandedShelfContentsRendererItem> Items { get; set; }
    }

    public partial class ExpandedShelfContentsRendererItem
    {
        [JsonProperty("videoRenderer")]
        public VideoRenderer VideoRenderer { get; set; }
    }

    public partial class VideoRenderer
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("thumbnail")]
        public ChannelThumbnailWithLinkRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("title")]
        public PurpleTitle Title { get; set; }

        [JsonProperty("descriptionSnippet")]
        public DescriptionSnippet DescriptionSnippet { get; set; }

        [JsonProperty("longBylineText")]
        public LongBylineTextClass LongBylineText { get; set; }

        [JsonProperty("publishedTimeText")]
        public PublishedTimeTextClass PublishedTimeText { get; set; }

        [JsonProperty("lengthText")]
        public Text LengthText { get; set; }

        [JsonProperty("viewCountText")]
        public PublishedTimeTextClass ViewCountText { get; set; }

        [JsonProperty("navigationEndpoint")]
        public VideoRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("ownerBadges")]
        public List<OwnerBadge> OwnerBadges { get; set; }

        [JsonProperty("ownerText")]
        public LongBylineTextClass OwnerText { get; set; }

        [JsonProperty("shortBylineText")]
        public LongBylineTextClass ShortBylineText { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("showActionMenu")]
        public bool ShowActionMenu { get; set; }

        [JsonProperty("shortViewCountText")]
        public PublishedTimeTextClass ShortViewCountText { get; set; }

        [JsonProperty("menu")]
        public Menu Menu { get; set; }

        [JsonProperty("channelThumbnailSupportedRenderers")]
        public ChannelThumbnailSupportedRenderers ChannelThumbnailSupportedRenderers { get; set; }

        [JsonProperty("thumbnailOverlays")]
        public List<ThumbnailOverlay> ThumbnailOverlays { get; set; }

        [JsonProperty("richThumbnail")]
        public RichThumbnail RichThumbnail { get; set; }
    }

    public partial class ChannelThumbnailSupportedRenderers
    {
        [JsonProperty("channelThumbnailWithLinkRenderer")]
        public ChannelThumbnailWithLinkRenderer ChannelThumbnailWithLinkRenderer { get; set; }
    }

    public partial class ChannelThumbnailWithLinkRenderer
    {
        [JsonProperty("thumbnail")]
        public ChannelThumbnailWithLinkRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("navigationEndpoint")]
        public ChannelThumbnailWithLinkRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("accessibility")]
        public Accessibility Accessibility { get; set; }
    }

    public partial class Accessibility
    {
        [JsonProperty("accessibilityData")]
        public AccessibilityData AccessibilityData { get; set; }
    }

    public partial class AccessibilityData
    {
        [JsonProperty("label")]
        public string Label { get; set; }
    }

    public partial class ChannelThumbnailWithLinkRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("browseEndpoint")]
        public BrowseEndpoint BrowseEndpoint { get; set; }
    }

    public partial class BrowseEndpoint
    {
        [JsonProperty("browseId")]
        public string BrowseId { get; set; }

        [JsonProperty("canonicalBaseUrl")]
        public string CanonicalBaseUrl { get; set; }
    }

    public partial class NavigationEndpointCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public PurpleWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class PurpleWebCommandMetadata
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("webPageType")]
        public string WebPageType { get; set; }

        [JsonProperty("rootVe")]
        public long RootVe { get; set; }

        [JsonProperty("apiUrl")]
        public string ApiUrl { get; set; }
    }

    public partial class ChannelThumbnailWithLinkRendererThumbnail
    {
        [JsonProperty("thumbnails")]
        public List<ThumbnailElement> Thumbnails { get; set; }
    }

    public partial class ThumbnailElement
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }
    }

    public partial class DescriptionSnippet
    {
        [JsonProperty("runs")]
        public List<DescriptionSnippetRun> Runs { get; set; }
    }

    public partial class DescriptionSnippetRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class Text
    {
        [JsonProperty("accessibility")]
        public Accessibility Accessibility { get; set; }

        [JsonProperty("simpleText")]
        public string SimpleText { get; set; }
    }

    public partial class LongBylineTextClass
    {
        [JsonProperty("runs")]
        public List<LongBylineTextRun> Runs { get; set; }
    }

    public partial class LongBylineTextRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("navigationEndpoint")]
        public ChannelThumbnailWithLinkRendererNavigationEndpoint NavigationEndpoint { get; set; }
    }

    public partial class Menu
    {
        [JsonProperty("menuRenderer")]
        public MenuRenderer MenuRenderer { get; set; }
    }

    public partial class MenuRenderer
    {
        [JsonProperty("items")]
        public List<MenuRendererItem> Items { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("accessibility")]
        public Accessibility Accessibility { get; set; }
    }

    public partial class MenuRendererItem
    {
        [JsonProperty("menuServiceItemRenderer")]
        public MenuServiceItemRenderer MenuServiceItemRenderer { get; set; }
    }

    public partial class MenuServiceItemRenderer
    {
        [JsonProperty("text")]
        public DescriptionSnippet Text { get; set; }

        [JsonProperty("icon")]
        public Icon Icon { get; set; }

        [JsonProperty("serviceEndpoint")]
        public ServiceEndpoint ServiceEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class Icon
    {
        [JsonProperty("iconType")]
        public string IconType { get; set; }
    }

    public partial class ServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ServiceEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public SignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class ServiceEndpointCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public FluffyWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class FluffyWebCommandMetadata
    {
        [JsonProperty("sendPost")]
        public bool SendPost { get; set; }
    }

    public partial class SignalServiceEndpoint
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }

        [JsonProperty("actions")]
        public List<SignalServiceEndpointAction> Actions { get; set; }
    }

    public partial class SignalServiceEndpointAction
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("addToPlaylistCommand")]
        public AddToPlaylistCommand AddToPlaylistCommand { get; set; }
    }

    public partial class AddToPlaylistCommand
    {
        [JsonProperty("openMiniplayer")]
        public bool OpenMiniplayer { get; set; }

        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("listType")]
        public string ListType { get; set; }

        [JsonProperty("onCreateListCommand")]
        public OnCreateListCommand OnCreateListCommand { get; set; }

        [JsonProperty("videoIds")]
        public List<string> VideoIds { get; set; }
    }

    public partial class OnCreateListCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("createPlaylistServiceEndpoint")]
        public CreatePlaylistServiceEndpoint CreatePlaylistServiceEndpoint { get; set; }
    }

    public partial class OnCreateListCommandCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public TentacledWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class TentacledWebCommandMetadata
    {
        [JsonProperty("sendPost")]
        public bool SendPost { get; set; }

        [JsonProperty("apiUrl")]
        public string ApiUrl { get; set; }
    }

    public partial class CreatePlaylistServiceEndpoint
    {
        [JsonProperty("videoIds")]
        public List<string> VideoIds { get; set; }

        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class VideoRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("watchEndpoint")]
        public WatchEndpoint WatchEndpoint { get; set; }
    }

    public partial class WatchEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }
    }

    public partial class OwnerBadge
    {
        [JsonProperty("metadataBadgeRenderer")]
        public MetadataBadgeRenderer MetadataBadgeRenderer { get; set; }
    }

    public partial class MetadataBadgeRenderer
    {
        [JsonProperty("icon")]
        public Icon Icon { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class PublishedTimeTextClass
    {
        [JsonProperty("simpleText")]
        public string SimpleText { get; set; }
    }

    public partial class RichThumbnail
    {
        [JsonProperty("movingThumbnailRenderer")]
        public MovingThumbnailRenderer MovingThumbnailRenderer { get; set; }
    }

    public partial class MovingThumbnailRenderer
    {
        [JsonProperty("movingThumbnailDetails")]
        public MovingThumbnailDetails MovingThumbnailDetails { get; set; }

        [JsonProperty("enableHoveredLogging")]
        public bool EnableHoveredLogging { get; set; }

        [JsonProperty("enableOverlay")]
        public bool EnableOverlay { get; set; }
    }

    public partial class MovingThumbnailDetails
    {
        [JsonProperty("thumbnails")]
        public List<ThumbnailElement> Thumbnails { get; set; }

        [JsonProperty("logAsMovingThumbnail")]
        public bool LogAsMovingThumbnail { get; set; }
    }

    public partial class ThumbnailOverlay
    {
        [JsonProperty("thumbnailOverlayTimeStatusRenderer")]
        public ThumbnailOverlayTimeStatusRenderer ThumbnailOverlayTimeStatusRenderer { get; set; }

        [JsonProperty("thumbnailOverlayToggleButtonRenderer")]
        public ThumbnailOverlayToggleButtonRenderer ThumbnailOverlayToggleButtonRenderer { get; set; }

        [JsonProperty("thumbnailOverlayNowPlayingRenderer")]
        public ThumbnailOverlayNowPlayingRenderer ThumbnailOverlayNowPlayingRenderer { get; set; }
    }

    public partial class ThumbnailOverlayNowPlayingRenderer
    {
        [JsonProperty("text")]
        public DescriptionSnippet Text { get; set; }
    }

    public partial class ThumbnailOverlayTimeStatusRenderer
    {
        [JsonProperty("text")]
        public Text Text { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }
    }

    public partial class ThumbnailOverlayToggleButtonRenderer
    {
        [JsonProperty("isToggled")]
        public bool? IsToggled { get; set; }

        [JsonProperty("untoggledIcon")]
        public Icon UntoggledIcon { get; set; }

        [JsonProperty("toggledIcon")]
        public Icon ToggledIcon { get; set; }

        [JsonProperty("untoggledTooltip")]
        public string UntoggledTooltip { get; set; }

        [JsonProperty("toggledTooltip")]
        public string ToggledTooltip { get; set; }

        [JsonProperty("untoggledServiceEndpoint")]
        public UntoggledServiceEndpoint UntoggledServiceEndpoint { get; set; }

        [JsonProperty("toggledServiceEndpoint")]
        public ToggledServiceEndpoint ToggledServiceEndpoint { get; set; }

        [JsonProperty("untoggledAccessibility")]
        public Accessibility UntoggledAccessibility { get; set; }

        [JsonProperty("toggledAccessibility")]
        public Accessibility ToggledAccessibility { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class ToggledServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("playlistEditEndpoint")]
        public ToggledServiceEndpointPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }
    }

    public partial class ToggledServiceEndpointPlaylistEditEndpoint
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("actions")]
        public List<PurpleAction> Actions { get; set; }
    }

    public partial class PurpleAction
    {
        [JsonProperty("action")]
        public string Action { get; set; }

        [JsonProperty("removedVideoId")]
        public string RemovedVideoId { get; set; }
    }

    public partial class UntoggledServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("playlistEditEndpoint")]
        public UntoggledServiceEndpointPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public SignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class UntoggledServiceEndpointPlaylistEditEndpoint
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("actions")]
        public List<FluffyAction> Actions { get; set; }
    }

    public partial class FluffyAction
    {
        [JsonProperty("addedVideoId")]
        public string AddedVideoId { get; set; }

        [JsonProperty("action")]
        public string Action { get; set; }
    }

    public partial class PurpleTitle
    {
        [JsonProperty("runs")]
        public List<DescriptionSnippetRun> Runs { get; set; }

        [JsonProperty("accessibility")]
        public Accessibility Accessibility { get; set; }
    }

    public partial class Header
    {
        [JsonProperty("textHeaderRenderer")]
        public TextHeaderRenderer TextHeaderRenderer { get; set; }
    }

    public partial class TextHeaderRenderer
    {
        [JsonProperty("title")]
        public PublishedTimeTextClass Title { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }
    }

  
}
