// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using YoutubeAPI.Models;
//
//    var temperatures = Temperatures.FromJson(jsonString);

namespace YoutubeAPI.Models.PlayList
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Temperatures
    {
        [JsonProperty("responseContext")]
        public ResponseContext ResponseContext { get; set; }

        [JsonProperty("estimatedResults")]
        
        public long EstimatedResults { get; set; }

        [JsonProperty("contents")]
        public Contents Contents { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("topbar")]
        public Topbar Topbar { get; set; }

        [JsonProperty("adSafetyReason")]
        public AdSafetyReason AdSafetyReason { get; set; }
    }

    public partial class AdSafetyReason
    {
        [JsonProperty("apmUserPreference")]
        public ApmUserPreference ApmUserPreference { get; set; }
    }

    public partial class ApmUserPreference
    {
    }

    public partial class Contents
    {
        [JsonProperty("twoColumnSearchResultsRenderer")]
        public TwoColumnSearchResultsRenderer TwoColumnSearchResultsRenderer { get; set; }
    }

    public partial class TwoColumnSearchResultsRenderer
    {
        [JsonProperty("primaryContents")]
        public PrimaryContents PrimaryContents { get; set; }
    }

    public partial class PrimaryContents
    {
        [JsonProperty("sectionListRenderer")]
        public SectionListRenderer SectionListRenderer1 { get; set; }
        [JsonProperty("richGridRenderer")]
        public SectionListRenderer SectionListRenderer2 { get; set; }
    }

    public partial class SectionListRenderer
    {
        [JsonProperty("contents")]
        public List<SectionListRendererContent> Contents { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("subMenu")]
        public SubMenu SubMenu { get; set; }

        [JsonProperty("hideBottomSeparator")]
        public bool HideBottomSeparator { get; set; }

        [JsonProperty("targetId")]
        public string TargetId { get; set; }
    }

    public partial class SectionListRendererContent
    {
        [JsonProperty("itemSectionRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ItemSectionRenderer ItemSectionRenderer1 { get; set; }
        [JsonProperty("richGridRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ItemSectionRenderer ItemSectionRenderer2 { get; set; }

        [JsonProperty("continuationItemRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ContinuationItemRenderer ContinuationItemRenderer { get; set; }
    }

    public partial class ContinuationItemRenderer
    {
        [JsonProperty("trigger")]
        public string Trigger { get; set; }

        [JsonProperty("continuationEndpoint")]
        public ContinuationEndpoint ContinuationEndpoint { get; set; }
    }

    public partial class ContinuationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("continuationCommand")]
        public ContinuationCommand ContinuationCommand { get; set; }
    }

    public partial class ContinuationEndpointCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public PurpleWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class PurpleWebCommandMetadata
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("sendPost")]
        public bool SendPost { get; set; }

        [JsonProperty("apiUrl")]
        public string ApiUrl { get; set; }
    }

    public partial class ContinuationCommand
    {
        [JsonProperty("token")]
        public string Token { get; set; }

        [JsonProperty("request")]
        public string Request { get; set; }
    }

    public partial class ItemSectionRenderer
    {
        [JsonProperty("contents")]
        public List<ItemSectionRendererContent> Contents { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        //[JsonProperty("content")]
        //public ContentData ContentData { get; set; }
    }

    public partial class ContentData
    {
        [JsonProperty("playlistRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public PlaylistRenderer PlaylistRenderer { get; set; }
    }

    public partial class ItemSectionRendererContent
    {
        [JsonProperty("searchPyvRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public SearchPyvRenderer SearchPyvRenderer { get; set; }

        [JsonProperty("playlistRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public PlaylistRenderer PlaylistRenderer { get; set; }

        [JsonProperty("richItemRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public RichItemRenderer RichRenderer { get; set; }
    }

    public partial class RichItemRenderer
    {
        [JsonProperty("content")]
        public RichItemContent Content { get; set; }
    }

    public partial class RichItemContent
    {

        [JsonProperty("playlistRenderer")]
        public PlaylistRenderer PlaylistRenderer { get; set; }
    }

    public partial class PlaylistRenderer
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("title")]
        public Title Title { get; set; }

        [JsonProperty("thumbnails")]
        public List<PlaylistVideoThumbnailRendererThumbnail> Thumbnails { get; set; }

        [JsonProperty("videoCount")]
       
        public long VideoCount { get; set; }

        [JsonProperty("navigationEndpoint")]
        public PlaylistRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("viewPlaylistText")]
        public ViewPlaylistText ViewPlaylistText { get; set; }

        [JsonProperty("shortBylineText")]
        public BylineText ShortBylineText { get; set; }

        [JsonProperty("publishedTimeText", NullValueHandling = NullValueHandling.Ignore)]
        public Title PublishedTimeText { get; set; }

        [JsonProperty("videos")]
        public List<Video> Videos { get; set; }

        [JsonProperty("videoCountText")]
        public TitleClass VideoCountText { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("thumbnailText")]
        public ThumbnailText ThumbnailText { get; set; }

        [JsonProperty("longBylineText")]
        public BylineText LongBylineText { get; set; }

        [JsonProperty("thumbnailRenderer")]
        public ThumbnailRenderer ThumbnailRenderer { get; set; }

        [JsonProperty("thumbnailOverlays")]
        public List<PlaylistRendererThumbnailOverlay> ThumbnailOverlays { get; set; }

        [JsonProperty("ownerBadges", NullValueHandling = NullValueHandling.Ignore)]
        public List<OwnerBadge> OwnerBadges { get; set; }
    }

    public partial class BylineText
    {
        [JsonProperty("runs")]
        public List<LongBylineTextRun> Runs { get; set; }
    }

    public partial class LongBylineTextRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("navigationEndpoint")]
        public PurpleNavigationEndpoint NavigationEndpoint { get; set; }
    }

    public partial class PurpleNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public EndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("browseEndpoint")]
        public PurpleBrowseEndpoint BrowseEndpoint { get; set; }
    }

    public partial class PurpleBrowseEndpoint
    {
        [JsonProperty("browseId")]
        public string BrowseId { get; set; }

        [JsonProperty("canonicalBaseUrl", NullValueHandling = NullValueHandling.Ignore)]
        public string CanonicalBaseUrl { get; set; }
    }

    public partial class EndpointCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public FluffyWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class FluffyWebCommandMetadata
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("webPageType")]
        public string WebPageType { get; set; }

        [JsonProperty("rootVe")]
        public long RootVe { get; set; }
    }

    public partial class PlaylistRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public EndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("watchEndpoint")]
        public PurpleWatchEndpoint WatchEndpoint { get; set; }
    }

    public partial class PurpleWatchEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class OwnerBadge
    {
        [JsonProperty("metadataBadgeRenderer")]
        public MetadataBadgeRenderer MetadataBadgeRenderer { get; set; }
    }

    public partial class MetadataBadgeRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class IconImage
    {
        [JsonProperty("iconType")]
        public string IconType { get; set; }
    }

    public partial class Title
    {
        [JsonProperty("simpleText")]
        public string SimpleText { get; set; }
    }

    public partial class PlaylistRendererThumbnailOverlay
    {
        [JsonProperty("thumbnailOverlaySidePanelRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlaySidePanelRenderer ThumbnailOverlaySidePanelRenderer { get; set; }

        [JsonProperty("thumbnailOverlayHoverTextRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayHoverTextRenderer ThumbnailOverlayHoverTextRenderer { get; set; }

        [JsonProperty("thumbnailOverlayNowPlayingRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayNowPlayingRenderer ThumbnailOverlayNowPlayingRenderer { get; set; }
    }

    public partial class ThumbnailOverlayHoverTextRenderer
    {
        [JsonProperty("text")]
        public TitleClass Text { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }
    }

    public partial class TitleClass
    {
        [JsonProperty("runs")]
        public List<TextRun> Runs { get; set; }
    }

    public partial class TextRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class ThumbnailOverlayNowPlayingRenderer
    {
        [JsonProperty("text")]
        public TitleClass Text { get; set; }
    }

    public partial class ThumbnailOverlaySidePanelRenderer
    {
        [JsonProperty("text")]
        public Title Text { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }
    }

    public partial class ThumbnailRenderer
    {
        [JsonProperty("playlistVideoThumbnailRenderer")]
        public PlaylistVideoThumbnailRenderer PlaylistVideoThumbnailRenderer { get; set; }
    }

    public partial class PlaylistVideoThumbnailRenderer
    {
        [JsonProperty("thumbnail")]
        public PlaylistVideoThumbnailRendererThumbnail Thumbnail { get; set; }
    }

    public partial class PlaylistVideoThumbnailRendererThumbnail
    {
        [JsonProperty("thumbnails")]
        public List<ThumbnailThumbnail> Thumbnails { get; set; }
    }

    public partial class ThumbnailThumbnail
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }
    }

    public partial class ThumbnailText
    {
        [JsonProperty("runs")]
        public List<ThumbnailTextRun> Runs { get; set; }
    }

    public partial class ThumbnailTextRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("bold", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Bold { get; set; }
    }

    public partial class Video
    {
        [JsonProperty("childVideoRenderer")]
        public ChildVideoRenderer ChildVideoRenderer { get; set; }
    }

    public partial class ChildVideoRenderer
    {
        [JsonProperty("title")]
        public Title Title { get; set; }

        [JsonProperty("navigationEndpoint")]
        public ChildVideoRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("lengthText")]
        public LengthTextClass LengthText { get; set; }

        [JsonProperty("videoId")]
        public string VideoId { get; set; }
    }

    public partial class LengthTextClass
    {
        [JsonProperty("accessibility")]
        public HotkeyAccessibilityLabelClass Accessibility { get; set; }

        [JsonProperty("simpleText")]
        public string SimpleText { get; set; }
    }

    public partial class HotkeyAccessibilityLabelClass
    {
        [JsonProperty("accessibilityData")]
        public AccessibilityAccessibilityData AccessibilityData { get; set; }
    }

    public partial class AccessibilityAccessibilityData
    {
        [JsonProperty("label")]
        public string Label { get; set; }
    }

    public partial class ChildVideoRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public EndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("watchEndpoint")]
        public FluffyWatchEndpoint WatchEndpoint { get; set; }
    }

    public partial class FluffyWatchEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }
    }

    public partial class ViewPlaylistText
    {
        [JsonProperty("runs")]
        public List<ViewPlaylistTextRun> Runs { get; set; }
    }

    public partial class ViewPlaylistTextRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("navigationEndpoint")]
        public Endpoint NavigationEndpoint { get; set; }
    }

    public partial class Endpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public EndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("browseEndpoint")]
        public EndpointBrowseEndpoint BrowseEndpoint { get; set; }
    }

    public partial class EndpointBrowseEndpoint
    {
        [JsonProperty("browseId")]
        public string BrowseId { get; set; }
    }

    public partial class SearchPyvRenderer
    {
        [JsonProperty("ads")]
        public List<Ad> Ads { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class Ad
    {
        [JsonProperty("promotedVideoRenderer")]
        public PromotedVideoRenderer PromotedVideoRenderer { get; set; }
    }

    public partial class PromotedVideoRenderer
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("thumbnail")]
        public PlaylistVideoThumbnailRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("title")]
        public Title Title { get; set; }

        [JsonProperty("description")]
        public Title Description { get; set; }

        [JsonProperty("longBylineText")]
        public BylineText LongBylineText { get; set; }

        [JsonProperty("shortBylineText")]
        public BylineText ShortBylineText { get; set; }

        [JsonProperty("lengthText")]
        public LengthTextClass LengthText { get; set; }

        [JsonProperty("navigationEndpoint")]
        public NextEndpointClass NavigationEndpoint { get; set; }

        [JsonProperty("impressionUrls")]
        public List<Uri> ImpressionUrls { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("menu")]
        public Menu Menu { get; set; }

        [JsonProperty("viewCountText")]
        public Title ViewCountText { get; set; }

        [JsonProperty("thumbnailOverlays")]
        public List<PromotedVideoRendererThumbnailOverlay> ThumbnailOverlays { get; set; }

        [JsonProperty("richThumbnail")]
        public RichThumbnail RichThumbnail { get; set; }

        [JsonProperty("adPlaybackContextParams")]
        public string AdPlaybackContextParams { get; set; }
    }

    public partial class Menu
    {
        [JsonProperty("menuRenderer")]
        public MenuMenuRenderer MenuRenderer { get; set; }
    }

    public partial class MenuMenuRenderer
    {
        [JsonProperty("items")]
        public List<MenuRendererItem> Items { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class MenuRendererItem
    {
        [JsonProperty("menuNavigationItemRenderer")]
        public MenuNavigationItemRenderer MenuNavigationItemRenderer { get; set; }
    }

    public partial class MenuNavigationItemRenderer
    {
        [JsonProperty("text")]
        public TitleClass Text { get; set; }

        [JsonProperty("navigationEndpoint")]
        public MenuNavigationItemRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class MenuNavigationItemRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public PurpleCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("adInfoDialogEndpoint")]
        public AdInfoDialogEndpoint AdInfoDialogEndpoint { get; set; }
    }

    public partial class AdInfoDialogEndpoint
    {
        [JsonProperty("dialog")]
        public Dialog Dialog { get; set; }
    }

    public partial class Dialog
    {
        [JsonProperty("adInfoDialogRenderer")]
        public AdInfoDialogRenderer AdInfoDialogRenderer { get; set; }
    }

    public partial class AdInfoDialogRenderer
    {
        [JsonProperty("dialogMessage")]
        public DialogMessage DialogMessage { get; set; }

        [JsonProperty("confirmLabel")]
        public Title ConfirmLabel { get; set; }

        [JsonProperty("confirmServiceEndpoint")]
        public ConfirmServiceEndpointClass ConfirmServiceEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("title")]
        public Title Title { get; set; }

        [JsonProperty("adReasons")]
        public List<Title> AdReasons { get; set; }

        [JsonProperty("impressionEndpoints")]
        public List<ConfirmServiceEndpointClass> ImpressionEndpoints { get; set; }
    }

    public partial class ConfirmServiceEndpointClass
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("loggingUrls")]
        public List<LoggingUrl> LoggingUrls { get; set; }

        [JsonProperty("pingingEndpoint")]
        public PingingEndpoint PingingEndpoint { get; set; }
    }

    public partial class LoggingUrl
    {
        [JsonProperty("baseUrl")]
        public Uri BaseUrl { get; set; }
    }

    public partial class PingingEndpoint
    {
        [JsonProperty("hack")]
        public bool Hack { get; set; }
    }

    public partial class DialogMessage
    {
        [JsonProperty("runs")]
        public List<DialogMessageRun> Runs { get; set; }
    }

    public partial class DialogMessageRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("navigationEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public CompactLinkRendererNavigationEndpoint NavigationEndpoint { get; set; }
    }

    public partial class CompactLinkRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("loggingUrls", NullValueHandling = NullValueHandling.Ignore)]
        public List<LoggingUrl> LoggingUrls { get; set; }

        [JsonProperty("commandMetadata")]
        public EndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("urlEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public PurpleUrlEndpoint UrlEndpoint { get; set; }

        [JsonProperty("signInEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public PurpleSignInEndpoint SignInEndpoint { get; set; }
    }

    public partial class PurpleSignInEndpoint
    {
        [JsonProperty("nextEndpoint")]
        public NextEndpointClass NextEndpoint { get; set; }
    }

    public partial class NextEndpointClass
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public EndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("urlEndpoint")]
        public NextEndpointUrlEndpoint UrlEndpoint { get; set; }
    }

    public partial class NextEndpointUrlEndpoint
    {
        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public partial class PurpleUrlEndpoint
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("target")]
        public string Target { get; set; }
    }

    public partial class PurpleCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public TentacledWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class TentacledWebCommandMetadata
    {
        [JsonProperty("ignoreNavigation")]
        public bool IgnoreNavigation { get; set; }
    }

    public partial class RichThumbnail
    {
        [JsonProperty("movingThumbnailRenderer")]
        public MovingThumbnailRenderer MovingThumbnailRenderer { get; set; }
    }

    public partial class MovingThumbnailRenderer
    {
        [JsonProperty("movingThumbnailDetails")]
        public MovingThumbnailDetails MovingThumbnailDetails { get; set; }

        [JsonProperty("enableHoveredLogging")]
        public bool EnableHoveredLogging { get; set; }

        [JsonProperty("enableOverlay")]
        public bool EnableOverlay { get; set; }
    }

    public partial class MovingThumbnailDetails
    {
        [JsonProperty("thumbnails")]
        public List<ThumbnailThumbnail> Thumbnails { get; set; }

        [JsonProperty("logAsMovingThumbnail")]
        public bool LogAsMovingThumbnail { get; set; }
    }

    public partial class PromotedVideoRendererThumbnailOverlay
    {
        [JsonProperty("thumbnailOverlayTimeStatusRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayTimeStatusRenderer ThumbnailOverlayTimeStatusRenderer { get; set; }

        [JsonProperty("thumbnailOverlayToggleButtonRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayToggleButtonRenderer ThumbnailOverlayToggleButtonRenderer { get; set; }
    }

    public partial class ThumbnailOverlayTimeStatusRenderer
    {
        [JsonProperty("text")]
        public LengthTextClass Text { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }
    }

    public partial class ThumbnailOverlayToggleButtonRenderer
    {
        [JsonProperty("isToggled")]
        public bool IsToggled { get; set; }

        [JsonProperty("untoggledIcon")]
        public IconImage UntoggledIcon { get; set; }

        [JsonProperty("toggledIcon")]
        public IconImage ToggledIcon { get; set; }

        [JsonProperty("untoggledTooltip")]
        public string UntoggledTooltip { get; set; }

        [JsonProperty("toggledTooltip")]
        public string ToggledTooltip { get; set; }

        [JsonProperty("untoggledServiceEndpoint")]
        public UntoggledServiceEndpoint UntoggledServiceEndpoint { get; set; }

        [JsonProperty("toggledServiceEndpoint")]
        public ToggledServiceEndpoint ToggledServiceEndpoint { get; set; }

        [JsonProperty("untoggledAccessibility")]
        public HotkeyAccessibilityLabelClass UntoggledAccessibility { get; set; }

        [JsonProperty("toggledAccessibility")]
        public HotkeyAccessibilityLabelClass ToggledAccessibility { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class ToggledServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("playlistEditEndpoint")]
        public ToggledServiceEndpointPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }
    }

    public partial class ToggledServiceEndpointPlaylistEditEndpoint
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("actions")]
        public List<PurpleAction> Actions { get; set; }
    }

    public partial class PurpleAction
    {
        [JsonProperty("action")]
        public string Action { get; set; }

        [JsonProperty("removedVideoId")]
        public string RemovedVideoId { get; set; }
    }

    public partial class UntoggledServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("playlistEditEndpoint")]
        public UntoggledServiceEndpointPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }
    }

    public partial class UntoggledServiceEndpointPlaylistEditEndpoint
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("actions")]
        public List<FluffyAction> Actions { get; set; }
    }

    public partial class FluffyAction
    {
        [JsonProperty("addedVideoId")]
        public string AddedVideoId { get; set; }

        [JsonProperty("action")]
        public string Action { get; set; }
    }

    public partial class SubMenu
    {
        [JsonProperty("searchSubMenuRenderer")]
        public SearchSubMenuRenderer SearchSubMenuRenderer { get; set; }
    }

    public partial class SearchSubMenuRenderer
    {
        [JsonProperty("title")]
        public TitleClass Title { get; set; }

        [JsonProperty("groups")]
        public List<Group> Groups { get; set; }

        [JsonProperty("clearAllText")]
        public TitleClass ClearAllText { get; set; }

        [JsonProperty("clearAllEndpoint")]
        public SearchEndpointClass ClearAllEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("button")]
        public Button Button { get; set; }
    }

    public partial class Button
    {
        [JsonProperty("toggleButtonRenderer")]
        public ToggleButtonRenderer ToggleButtonRenderer { get; set; }
    }

    public partial class ToggleButtonRenderer
    {
        [JsonProperty("style")]
        public Style Style { get; set; }

        [JsonProperty("isToggled")]
        public bool IsToggled { get; set; }

        [JsonProperty("isDisabled")]
        public bool IsDisabled { get; set; }

        [JsonProperty("defaultIcon")]
        public IconImage DefaultIcon { get; set; }

        [JsonProperty("defaultText")]
        public TitleClass DefaultText { get; set; }

        [JsonProperty("accessibility")]
        public AccessibilityAccessibilityData Accessibility { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("defaultTooltip")]
        public string DefaultTooltip { get; set; }

        [JsonProperty("toggledTooltip")]
        public string ToggledTooltip { get; set; }

        [JsonProperty("toggledStyle")]
        public Style ToggledStyle { get; set; }

        [JsonProperty("accessibilityData")]
        public HotkeyAccessibilityLabelClass AccessibilityData { get; set; }
    }

    public partial class Style
    {
        [JsonProperty("styleType")]
        public string StyleType { get; set; }
    }

    public partial class SearchEndpointClass
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public EndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("searchEndpoint")]
        public SearchEndpointSearchEndpoint SearchEndpoint { get; set; }
    }

    public partial class SearchEndpointSearchEndpoint
    {
        [JsonProperty("query")]
        public string Query { get; set; }
    }

    public partial class Group
    {
        [JsonProperty("searchFilterGroupRenderer")]
        public SearchFilterGroupRenderer SearchFilterGroupRenderer { get; set; }
    }

    public partial class SearchFilterGroupRenderer
    {
        [JsonProperty("title")]
        public Title Title { get; set; }

        [JsonProperty("filters")]
        public List<Filter> Filters { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class Filter
    {
        [JsonProperty("searchFilterRenderer")]
        public SearchFilterRenderer SearchFilterRenderer { get; set; }
    }

    public partial class SearchFilterRenderer
    {
        [JsonProperty("label")]
        public Title Label { get; set; }

        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("navigationEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public SearchFilterRendererNavigationEndpoint NavigationEndpoint { get; set; }
    }

    public partial class SearchFilterRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public EndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("searchEndpoint")]
        public NavigationEndpointSearchEndpoint SearchEndpoint { get; set; }
    }

    public partial class NavigationEndpointSearchEndpoint
    {
        [JsonProperty("query")]
        public string Query { get; set; }

        [JsonProperty("params", NullValueHandling = NullValueHandling.Ignore)]
        public string Params { get; set; }
    }

    public partial class ResponseContext
    {
        [JsonProperty("serviceTrackingParams")]
        public List<ServiceTrackingParam> ServiceTrackingParams { get; set; }

        [JsonProperty("webResponseContextExtensionData")]
        public WebResponseContextExtensionData WebResponseContextExtensionData { get; set; }
    }

    public partial class ServiceTrackingParam
    {
        [JsonProperty("service")]
        public string Service { get; set; }

        [JsonProperty("params")]
        public List<Param> Params { get; set; }
    }

    public partial class Param
    {
        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }
    }

    public partial class WebResponseContextExtensionData
    {
        [JsonProperty("ytConfigData")]
        public YtConfigData YtConfigData { get; set; }

        [JsonProperty("hasDecorated")]
        public bool HasDecorated { get; set; }
    }

    public partial class YtConfigData
    {
        [JsonProperty("csn")]
        public string Csn { get; set; }

        [JsonProperty("visitorData")]
        public string VisitorData { get; set; }

        [JsonProperty("rootVisualElementType")]
        public long RootVisualElementType { get; set; }
    }

    public partial class Topbar
    {
        [JsonProperty("desktopTopbarRenderer")]
        public DesktopTopbarRenderer DesktopTopbarRenderer { get; set; }
    }

    public partial class DesktopTopbarRenderer
    {
        [JsonProperty("logo")]
        public Logo Logo { get; set; }

        [JsonProperty("searchbox")]
        public Searchbox Searchbox { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("countryCode")]
        public string CountryCode { get; set; }

        [JsonProperty("topbarButtons")]
        public List<TopbarButton> TopbarButtons { get; set; }

        [JsonProperty("hotkeyDialog")]
        public HotkeyDialog HotkeyDialog { get; set; }

        [JsonProperty("backButton")]
        public BackButtonClass BackButton { get; set; }

        [JsonProperty("forwardButton")]
        public BackButtonClass ForwardButton { get; set; }

        [JsonProperty("a11ySkipNavigationButton")]
        public A11YSkipNavigationButtonClass A11YSkipNavigationButton { get; set; }
    }

    public partial class A11YSkipNavigationButtonClass
    {
        [JsonProperty("buttonRenderer")]
        public A11YSkipNavigationButtonButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class A11YSkipNavigationButtonButtonRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("isDisabled")]
        public bool IsDisabled { get; set; }

        [JsonProperty("text")]
        public TitleClass Text { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("command", NullValueHandling = NullValueHandling.Ignore)]
        public Command Command { get; set; }
    }

    public partial class Command
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public CommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public CommandSignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class CommandCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public StickyWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class StickyWebCommandMetadata
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("sendPost")]
        public bool SendPost { get; set; }
    }

    public partial class CommandSignalServiceEndpoint
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }

        [JsonProperty("actions")]
        public List<TentacledAction> Actions { get; set; }
    }

    public partial class TentacledAction
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("signalAction")]
        public SignalAction SignalAction { get; set; }
    }

    public partial class SignalAction
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }
    }

    public partial class BackButtonClass
    {
        [JsonProperty("buttonRenderer")]
        public BackButtonButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class BackButtonButtonRenderer
    {
        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("command")]
        public Command Command { get; set; }
    }

    public partial class HotkeyDialog
    {
        [JsonProperty("hotkeyDialogRenderer")]
        public HotkeyDialogRenderer HotkeyDialogRenderer { get; set; }
    }

    public partial class HotkeyDialogRenderer
    {
        [JsonProperty("title")]
        public TitleClass Title { get; set; }

        [JsonProperty("sections")]
        public List<HotkeyDialogRendererSection> Sections { get; set; }

        [JsonProperty("dismissButton")]
        public A11YSkipNavigationButtonClass DismissButton { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class HotkeyDialogRendererSection
    {
        [JsonProperty("hotkeyDialogSectionRenderer")]
        public HotkeyDialogSectionRenderer HotkeyDialogSectionRenderer { get; set; }
    }

    public partial class HotkeyDialogSectionRenderer
    {
        [JsonProperty("title")]
        public TitleClass Title { get; set; }

        [JsonProperty("options")]
        public List<Option> Options { get; set; }
    }

    public partial class Option
    {
        [JsonProperty("hotkeyDialogSectionOptionRenderer")]
        public HotkeyDialogSectionOptionRenderer HotkeyDialogSectionOptionRenderer { get; set; }
    }

    public partial class HotkeyDialogSectionOptionRenderer
    {
        [JsonProperty("label")]
        public TitleClass Label { get; set; }

        [JsonProperty("hotkey")]
        public string Hotkey { get; set; }

        [JsonProperty("hotkeyAccessibilityLabel", NullValueHandling = NullValueHandling.Ignore)]
        public HotkeyAccessibilityLabelClass HotkeyAccessibilityLabel { get; set; }
    }

    public partial class Logo
    {
        [JsonProperty("topbarLogoRenderer")]
        public TopbarLogoRenderer TopbarLogoRenderer { get; set; }
    }

    public partial class TopbarLogoRenderer
    {
        [JsonProperty("iconImage")]
        public IconImage IconImage { get; set; }

        [JsonProperty("tooltipText")]
        public TitleClass TooltipText { get; set; }

        [JsonProperty("endpoint")]
        public Endpoint Endpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class Searchbox
    {
        [JsonProperty("fusionSearchboxRenderer")]
        public FusionSearchboxRenderer FusionSearchboxRenderer { get; set; }
    }

    public partial class FusionSearchboxRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("placeholderText")]
        public TitleClass PlaceholderText { get; set; }

        [JsonProperty("config")]
        public Config Config { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("searchEndpoint")]
        public SearchEndpointClass SearchEndpoint { get; set; }
    }

    public partial class Config
    {
        [JsonProperty("webSearchboxConfig")]
        public WebSearchboxConfig WebSearchboxConfig { get; set; }
    }

    public partial class WebSearchboxConfig
    {
        [JsonProperty("requestLanguage")]
        public string RequestLanguage { get; set; }

        [JsonProperty("requestDomain")]
        public string RequestDomain { get; set; }

        [JsonProperty("hasOnscreenKeyboard")]
        public bool HasOnscreenKeyboard { get; set; }

        [JsonProperty("focusSearchbox")]
        public bool FocusSearchbox { get; set; }
    }

    public partial class TopbarButton
    {
        [JsonProperty("topbarMenuButtonRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public TopbarMenuButtonRenderer TopbarMenuButtonRenderer { get; set; }

        [JsonProperty("buttonRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public TopbarButtonButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class TopbarButtonButtonRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("text")]
        public TitleClass Text { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("navigationEndpoint")]
        public ButtonRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("targetId")]
        public string TargetId { get; set; }
    }

    public partial class ButtonRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public EndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signInEndpoint")]
        public FluffySignInEndpoint SignInEndpoint { get; set; }
    }

    public partial class FluffySignInEndpoint
    {
        [JsonProperty("idamTag")]
      
        public long IdamTag { get; set; }
    }

    public partial class TopbarMenuButtonRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("menuRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public TopbarMenuButtonRendererMenuRenderer MenuRenderer { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("accessibility")]
        public HotkeyAccessibilityLabelClass Accessibility { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("targetId", NullValueHandling = NullValueHandling.Ignore)]
        public string TargetId { get; set; }

        [JsonProperty("menuRequest", NullValueHandling = NullValueHandling.Ignore)]
        public MenuRequest MenuRequest { get; set; }
    }

    public partial class TopbarMenuButtonRendererMenuRenderer
    {
        [JsonProperty("multiPageMenuRenderer")]
        public MenuRendererMultiPageMenuRenderer MultiPageMenuRenderer { get; set; }
    }

    public partial class MenuRendererMultiPageMenuRenderer
    {
        [JsonProperty("sections")]
        public List<MultiPageMenuRendererSection> Sections { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("style", NullValueHandling = NullValueHandling.Ignore)]
        public string Style { get; set; }
    }

    public partial class MultiPageMenuRendererSection
    {
        [JsonProperty("multiPageMenuSectionRenderer")]
        public MultiPageMenuSectionRenderer MultiPageMenuSectionRenderer { get; set; }
    }

    public partial class MultiPageMenuSectionRenderer
    {
        [JsonProperty("items")]
        public List<MultiPageMenuSectionRendererItem> Items { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class MultiPageMenuSectionRendererItem
    {
        [JsonProperty("compactLinkRenderer")]
        public CompactLinkRenderer CompactLinkRenderer { get; set; }
    }

    public partial class CompactLinkRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("title")]
        public TitleClass Title { get; set; }

        [JsonProperty("navigationEndpoint")]
        public CompactLinkRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("style", NullValueHandling = NullValueHandling.Ignore)]
        public string Style { get; set; }
    }

    public partial class MenuRequest
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public MenuRequestSignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class MenuRequestSignalServiceEndpoint
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }

        [JsonProperty("actions")]
        public List<StickyAction> Actions { get; set; }
    }

    public partial class StickyAction
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("openPopupAction")]
        public OpenPopupAction OpenPopupAction { get; set; }
    }

    public partial class OpenPopupAction
    {
        [JsonProperty("popup")]
        public Popup Popup { get; set; }

        [JsonProperty("popupType")]
        public string PopupType { get; set; }

        [JsonProperty("beReused")]
        public bool BeReused { get; set; }
    }

    public partial class Popup
    {
        [JsonProperty("multiPageMenuRenderer")]
        public PopupMultiPageMenuRenderer MultiPageMenuRenderer { get; set; }
    }

    public partial class PopupMultiPageMenuRenderer
    {
        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("showLoadingSpinner")]
        public bool ShowLoadingSpinner { get; set; }
    }

    



  

  

  

    
}
