// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using YoutubeAPI.Models;
//
//    var temperatures = Temperatures.FromJson(jsonString);

namespace YoutubeAPI.Models.List
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Temperatures
    {
        [JsonProperty("responseContext")]
        public ResponseContext ResponseContext { get; set; }

        [JsonProperty("contents")]
        public Contents Contents { get; set; }

        [JsonProperty("metadata")]
        public Metadata Metadata { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("topbar")]
        public Topbar Topbar { get; set; }

        [JsonProperty("microformat")]
        public Microformat Microformat { get; set; }

        [JsonProperty("sidebar")]
        public Sidebar Sidebar { get; set; }

        [JsonProperty("frameworkUpdates")]
        public FrameworkUpdates FrameworkUpdates { get; set; }
    }

    public partial class Contents
    {
        [JsonProperty("twoColumnBrowseResultsRenderer")]
        public TwoColumnBrowseResultsRenderer TwoColumnBrowseResultsRenderer { get; set; }
    }

    public partial class TwoColumnBrowseResultsRenderer
    {
        [JsonProperty("tabs")]
        public List<Tab> Tabs { get; set; }
    }

    public partial class Tab
    {
        [JsonProperty("tabRenderer")]
        public TabRenderer TabRenderer { get; set; }
    }

    public partial class TabRenderer
    {
        [JsonProperty("selected")]
        public bool Selected { get; set; }

        [JsonProperty("content")]
        public TabRendererContent Content { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class TabRendererContent
    {
        [JsonProperty("sectionListRenderer")]
        public SectionListRenderer SectionListRenderer { get; set; }
    }

    public partial class SectionListRenderer
    {
        [JsonProperty("contents")]
        public List<SectionListRendererContent> Contents { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class SectionListRendererContent
    {
        [JsonProperty("itemSectionRenderer")]
        public ItemSectionRenderer ItemSectionRenderer { get; set; }
    }

    public partial class ItemSectionRenderer
    {
        [JsonProperty("contents")]
        public List<ItemSectionRendererContent> Contents { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class ItemSectionRendererContent
    {
        [JsonProperty("playlistVideoListRenderer")]
        public PlaylistVideoListRenderer PlaylistVideoListRenderer { get; set; }
    }

    public partial class PlaylistVideoListRenderer
    {
        [JsonProperty("contents")]
        public List<PlaylistVideoListRendererContent> Contents { get; set; }

        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("isEditable")]
        public bool IsEditable { get; set; }

        [JsonProperty("canReorder")]
        public bool CanReorder { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("onReorderEndpoint")]
        public OnReorderEndpoint OnReorderEndpoint { get; set; }
    }

    public partial class PlaylistVideoListRendererContent
    {
        [JsonProperty("playlistVideoRenderer")]
        public PlaylistVideoRenderer PlaylistVideoRenderer { get; set; }
    }

    public partial class PlaylistVideoRenderer
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("thumbnail")]
        public PlaylistVideoRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("title")]
        public LengthText Title { get; set; }

        [JsonProperty("index")]
        public ShowMoreText Index { get; set; }

        [JsonProperty("shortBylineText")]
        public ShortBylineTextClass ShortBylineText { get; set; }

        [JsonProperty("lengthText")]
        public LengthText LengthText { get; set; }

        [JsonProperty("navigationEndpoint")]
        public PlaylistVideoRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("lengthSeconds")]
       
        public long LengthSeconds { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("isPlayable")]
        public bool IsPlayable { get; set; }

        [JsonProperty("menu")]
        public PlaylistVideoRendererMenu Menu { get; set; }

        [JsonProperty("isWatched")]
        public bool IsWatched { get; set; }

        [JsonProperty("thumbnailOverlays")]
        public List<PlaylistVideoRendererThumbnailOverlay> ThumbnailOverlays { get; set; }
    }

    public partial class ShowMoreText
    {
        [JsonProperty("simpleText")]
        public string SimpleText { get; set; }
    }

    public partial class LengthText
    {
        [JsonProperty("accessibility")]
        public SubscribeAccessibilityClass Accessibility { get; set; }

        [JsonProperty("simpleText")]
        public string SimpleText { get; set; }

        [JsonProperty("runs")]
        public List<ItemRun> Runs { get; set; }
    }

    public partial class ItemRun
    {
        [JsonProperty("text")]
        public String Text { get; set; }
    }

    public partial class SubscribeAccessibilityClass
    {
        [JsonProperty("accessibilityData")]
        public AccessibilityAccessibilityData AccessibilityData { get; set; }
    }

    public partial class AccessibilityAccessibilityData
    {
        [JsonProperty("label")]
        public string Label { get; set; }
    }

    public partial class PlaylistVideoRendererMenu
    {
        [JsonProperty("menuRenderer")]
        public PurpleMenuRenderer MenuRenderer { get; set; }
    }

    public partial class PurpleMenuRenderer
    {
        [JsonProperty("items")]
        public List<PurpleItem> Items { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("accessibility")]
        public SubscribeAccessibilityClass Accessibility { get; set; }
    }

    public partial class PurpleItem
    {
        [JsonProperty("menuServiceItemRenderer")]
        public PurpleMenuServiceItemRenderer MenuServiceItemRenderer { get; set; }
    }

    public partial class PurpleMenuServiceItemRenderer
    {
        [JsonProperty("text")]
        public TextElement Text { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("serviceEndpoint")]
        public PurpleServiceEndpoint ServiceEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("hasSeparator", NullValueHandling = NullValueHandling.Ignore)]
        public bool? HasSeparator { get; set; }
    }

    public partial class IconImage
    {
        [JsonProperty("iconType")]
        public string IconType { get; set; }
    }

    public partial class PurpleServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public PurpleSignalServiceEndpoint SignalServiceEndpoint { get; set; }

        [JsonProperty("playlistEditEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public ServiceEndpointPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }

        [JsonProperty("addToPlaylistServiceEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public AddToPlaylistServiceEndpoint AddToPlaylistServiceEndpoint { get; set; }
    }

    public partial class AddToPlaylistServiceEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }
    }

    public partial class OnCreateListCommandCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public PurpleWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class PurpleWebCommandMetadata
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("sendPost")]
        public bool SendPost { get; set; }

        [JsonProperty("apiUrl", NullValueHandling = NullValueHandling.Ignore)]
        public string ApiUrl { get; set; }
    }

    public partial class ServiceEndpointPlaylistEditEndpoint
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("actions")]
        public List<PurpleAction> Actions { get; set; }
    }

    public partial class PurpleAction
    {
        [JsonProperty("addedVideoId")]
        public string AddedVideoId { get; set; }

        [JsonProperty("action")]
        public string Action { get; set; }
    }

    public partial class PurpleSignalServiceEndpoint
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }

        [JsonProperty("actions")]
        public List<FluffyAction> Actions { get; set; }
    }

    public partial class FluffyAction
    {
        [JsonProperty("addToPlaylistCommand")]
        public AddToPlaylistCommand AddToPlaylistCommand { get; set; }
    }

    public partial class AddToPlaylistCommand
    {
        [JsonProperty("openMiniplayer")]
        public bool OpenMiniplayer { get; set; }

        [JsonProperty("openListPanel")]
        public bool OpenListPanel { get; set; }

        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("listType")]
        public string ListType { get; set; }

        [JsonProperty("onCreateListCommand")]
        public OnCreateListCommand OnCreateListCommand { get; set; }

        [JsonProperty("videoIds")]
        public List<string> VideoIds { get; set; }
    }

    public partial class OnCreateListCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("createPlaylistServiceEndpoint")]
        public CreatePlaylistServiceEndpoint CreatePlaylistServiceEndpoint { get; set; }
    }

    public partial class CreatePlaylistServiceEndpoint
    {
        [JsonProperty("videoIds")]
        public List<string> VideoIds { get; set; }

        [JsonProperty("hack")]
        public bool Hack { get; set; }

        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class TextElement
    {
        [JsonProperty("runs")]
        public List<TextRun> Runs { get; set; }
    }

    public partial class TextRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class PlaylistVideoRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("watchEndpoint")]
        public PurpleWatchEndpoint WatchEndpoint { get; set; }
    }

    public partial class NavigationEndpointCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public FluffyWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class FluffyWebCommandMetadata
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("webPageType")]
        public string WebPageType { get; set; }

        [JsonProperty("rootVe")]
        public long RootVe { get; set; }
    }

    public partial class PurpleWatchEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("index")]
        public long Index { get; set; }

        [JsonProperty("startTimeSeconds")]
        public long StartTimeSeconds { get; set; }
    }

    public partial class ShortBylineTextClass
    {
        [JsonProperty("runs")]
        public List<ShortBylineTextRun> Runs { get; set; }
    }

    public partial class ShortBylineTextRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("navigationEndpoint")]
        public Endpoint NavigationEndpoint { get; set; }
    }

    public partial class Endpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("browseEndpoint")]
        public EndpointBrowseEndpoint BrowseEndpoint { get; set; }
    }

    public partial class EndpointBrowseEndpoint
    {
        [JsonProperty("browseId")]
        public string BrowseId { get; set; }
    }

    public partial class PlaylistVideoRendererThumbnail
    {
        [JsonProperty("thumbnails")]
        public List<ThumbnailElement> Thumbnails { get; set; }
    }

    public partial class ThumbnailElement
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }
    }

    public partial class PlaylistVideoRendererThumbnailOverlay
    {
        [JsonProperty("thumbnailOverlayResumePlaybackRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayResumePlaybackRenderer ThumbnailOverlayResumePlaybackRenderer { get; set; }

        [JsonProperty("thumbnailOverlayTimeStatusRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayTimeStatusRenderer ThumbnailOverlayTimeStatusRenderer { get; set; }

        [JsonProperty("thumbnailOverlayNowPlayingRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayNowPlayingRenderer ThumbnailOverlayNowPlayingRenderer { get; set; }
    }

    public partial class ThumbnailOverlayNowPlayingRenderer
    {
        [JsonProperty("text")]
        public TextElement Text { get; set; }
    }

    public partial class ThumbnailOverlayResumePlaybackRenderer
    {
        [JsonProperty("percentDurationWatched")]
        public long PercentDurationWatched { get; set; }
    }

    public partial class ThumbnailOverlayTimeStatusRenderer
    {
        [JsonProperty("text")]
        public LengthText Text { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }
    }

    public partial class OnReorderEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("playlistEditEndpoint")]
        public OnReorderEndpointPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }
    }

    public partial class OnReorderEndpointPlaylistEditEndpoint
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("actions")]
        public List<TentacledAction> Actions { get; set; }

        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class TentacledAction
    {
        [JsonProperty("action")]
        public string Action { get; set; }
    }

    public partial class FrameworkUpdates
    {
        [JsonProperty("entityBatchUpdate")]
        public EntityBatchUpdate EntityBatchUpdate { get; set; }
    }

    public partial class EntityBatchUpdate
    {
        [JsonProperty("mutations")]
        public List<Mutation> Mutations { get; set; }
    }

    public partial class Mutation
    {
        [JsonProperty("entityKey")]
        public string EntityKey { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("payload")]
        public Payload Payload { get; set; }
    }

    public partial class Payload
    {
        [JsonProperty("subscriptionStateEntity")]
        public SubscriptionStateEntity SubscriptionStateEntity { get; set; }
    }

    public partial class SubscriptionStateEntity
    {
        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("subscribed")]
        public bool Subscribed { get; set; }
    }

    public partial class Metadata
    {
        [JsonProperty("playlistMetadataRenderer")]
        public PlaylistMetadataRenderer PlaylistMetadataRenderer { get; set; }
    }

    public partial class PlaylistMetadataRenderer
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("androidAppindexingLink")]
        public string AndroidAppindexingLink { get; set; }

        [JsonProperty("iosAppindexingLink")]
        public string IosAppindexingLink { get; set; }
    }

    public partial class Microformat
    {
        [JsonProperty("microformatDataRenderer")]
        public MicroformatDataRenderer MicroformatDataRenderer { get; set; }
    }

    public partial class MicroformatDataRenderer
    {
        [JsonProperty("urlCanonical")]
        public Uri UrlCanonical { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("thumbnail")]
        public PlaylistVideoRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("siteName")]
        public string SiteName { get; set; }

        [JsonProperty("appName")]
        public string AppName { get; set; }

        [JsonProperty("androidPackage")]
        public string AndroidPackage { get; set; }

        [JsonProperty("iosAppStoreId")]
      
        public long IosAppStoreId { get; set; }

        [JsonProperty("iosAppArguments")]
        public Uri IosAppArguments { get; set; }

        [JsonProperty("ogType")]
        public string OgType { get; set; }

        [JsonProperty("urlApplinksWeb")]
        public Uri UrlApplinksWeb { get; set; }

        [JsonProperty("urlApplinksIos")]
        public Uri UrlApplinksIos { get; set; }

        [JsonProperty("urlApplinksAndroid")]
        public Uri UrlApplinksAndroid { get; set; }

        [JsonProperty("urlTwitterIos")]
        public Uri UrlTwitterIos { get; set; }

        [JsonProperty("urlTwitterAndroid")]
        public Uri UrlTwitterAndroid { get; set; }

        [JsonProperty("twitterCardType")]
        public string TwitterCardType { get; set; }

        [JsonProperty("twitterSiteHandle")]
        public string TwitterSiteHandle { get; set; }

        [JsonProperty("schemaDotOrgType")]
        public Uri SchemaDotOrgType { get; set; }

        [JsonProperty("noindex")]
        public bool Noindex { get; set; }

        [JsonProperty("unlisted")]
        public bool Unlisted { get; set; }

        [JsonProperty("linkAlternates")]
        public List<LinkAlternate> LinkAlternates { get; set; }
    }

    public partial class LinkAlternate
    {
        [JsonProperty("hrefUrl")]
        public string HrefUrl { get; set; }
    }

    public partial class ResponseContext
    {
        [JsonProperty("serviceTrackingParams")]
        public List<ServiceTrackingParam> ServiceTrackingParams { get; set; }

        [JsonProperty("webResponseContextExtensionData")]
        public WebResponseContextExtensionData WebResponseContextExtensionData { get; set; }
    }

    public partial class ServiceTrackingParam
    {
        [JsonProperty("service")]
        public string Service { get; set; }

        [JsonProperty("params")]
        public List<Param> Params { get; set; }
    }

    public partial class Param
    {
        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }
    }

    public partial class WebResponseContextExtensionData
    {
        [JsonProperty("ytConfigData")]
        public YtConfigData YtConfigData { get; set; }

        [JsonProperty("hasDecorated")]
        public bool HasDecorated { get; set; }
    }

    public partial class YtConfigData
    {
        [JsonProperty("csn")]
        public string Csn { get; set; }

        [JsonProperty("visitorData")]
        public string VisitorData { get; set; }

        [JsonProperty("sessionIndex")]
        public long SessionIndex { get; set; }

        [JsonProperty("rootVisualElementType")]
        public long RootVisualElementType { get; set; }
    }

    public partial class Sidebar
    {
        [JsonProperty("playlistSidebarRenderer")]
        public PlaylistSidebarRenderer PlaylistSidebarRenderer { get; set; }
    }

    public partial class PlaylistSidebarRenderer
    {
        [JsonProperty("items")]
        public List<PlaylistSidebarRendererItem> Items { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class PlaylistSidebarRendererItem
    {
        [JsonProperty("playlistSidebarPrimaryInfoRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public PlaylistSidebarPrimaryInfoRenderer PlaylistSidebarPrimaryInfoRenderer { get; set; }

        [JsonProperty("playlistSidebarSecondaryInfoRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public PlaylistSidebarSecondaryInfoRenderer PlaylistSidebarSecondaryInfoRenderer { get; set; }
    }

    public partial class PlaylistSidebarPrimaryInfoRenderer
    {
        [JsonProperty("thumbnailRenderer")]
        public ThumbnailRenderer ThumbnailRenderer { get; set; }

        [JsonProperty("title")]
        public PlaylistSidebarPrimaryInfoRendererTitle Title { get; set; }

        [JsonProperty("stats")]
        public List<Stat> Stats { get; set; }

        [JsonProperty("menu")]
        public PlaylistSidebarPrimaryInfoRendererMenu Menu { get; set; }

        [JsonProperty("thumbnailOverlays")]
        public List<PlaylistSidebarPrimaryInfoRendererThumbnailOverlay> ThumbnailOverlays { get; set; }

        [JsonProperty("navigationEndpoint")]
        public PlaylistSidebarPrimaryInfoRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("showMoreText")]
        public ShowMoreText ShowMoreText { get; set; }
    }

    public partial class PlaylistSidebarPrimaryInfoRendererMenu
    {
        [JsonProperty("menuRenderer")]
        public FluffyMenuRenderer MenuRenderer { get; set; }
    }

    public partial class FluffyMenuRenderer
    {
        [JsonProperty("items")]
        public List<FluffyItem> Items { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("topLevelButtons")]
        public List<TopLevelButton> TopLevelButtons { get; set; }

        [JsonProperty("accessibility")]
        public SubscribeAccessibilityClass Accessibility { get; set; }
    }

    public partial class FluffyItem
    {
        [JsonProperty("menuServiceItemRenderer")]
        public FluffyMenuServiceItemRenderer MenuServiceItemRenderer { get; set; }
    }

    public partial class FluffyMenuServiceItemRenderer
    {
        [JsonProperty("text")]
        public TextElement Text { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("serviceEndpoint")]
        public FluffyServiceEndpoint ServiceEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class FluffyServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public CommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public FluffySignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class CommandCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public TentacledWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class TentacledWebCommandMetadata
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("sendPost")]
        public bool SendPost { get; set; }
    }

    public partial class FluffySignalServiceEndpoint
    {
        [JsonProperty("actions")]
        public List<StickyAction> Actions { get; set; }
    }

    public partial class StickyAction
    {
        [JsonProperty("openPopupAction")]
        public PurpleOpenPopupAction OpenPopupAction { get; set; }
    }

    public partial class PurpleOpenPopupAction
    {
        [JsonProperty("popup")]
        public PurplePopup Popup { get; set; }

        [JsonProperty("popupType")]
        public string PopupType { get; set; }
    }

    public partial class PurplePopup
    {
        [JsonProperty("confirmDialogRenderer")]
        public PurpleConfirmDialogRenderer ConfirmDialogRenderer { get; set; }
    }

    public partial class PurpleConfirmDialogRenderer
    {
        [JsonProperty("title")]
        public TextElement Title { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("dialogMessages")]
        public List<TextElement> DialogMessages { get; set; }

        [JsonProperty("confirmButton")]
        public DismissButtonClass ConfirmButton { get; set; }

        [JsonProperty("cancelButton")]
        public DismissButtonClass CancelButton { get; set; }
    }

    public partial class DismissButtonClass
    {
        [JsonProperty("buttonRenderer")]
        public DismissButtonButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class DismissButtonButtonRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("isDisabled")]
        public bool IsDisabled { get; set; }

        [JsonProperty("text")]
        public ShowMoreText Text { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("command", NullValueHandling = NullValueHandling.Ignore)]
        public ButtonRendererCommand Command { get; set; }

        [JsonProperty("serviceEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public TentacledServiceEndpoint ServiceEndpoint { get; set; }
    }

    public partial class ButtonRendererCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public CommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public CommandSignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class CommandSignalServiceEndpoint
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }

        [JsonProperty("actions")]
        public List<IndigoAction> Actions { get; set; }
    }

    public partial class IndigoAction
    {
        [JsonProperty("signalAction")]
        public Signal SignalAction { get; set; }
    }

    public partial class Signal
    {
        [JsonProperty("signal")]
        public string SignalSignal { get; set; }
    }

    public partial class TentacledServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("flagEndpoint")]
        public FlagEndpoint FlagEndpoint { get; set; }
    }

    public partial class FlagEndpoint
    {
        [JsonProperty("flagAction")]
        public string FlagAction { get; set; }
    }

    public partial class TopLevelButton
    {
        [JsonProperty("toggleButtonRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ToggleButtonRenderer ToggleButtonRenderer { get; set; }

        [JsonProperty("buttonRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public TopLevelButtonButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class TopLevelButtonButtonRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("navigationEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public ButtonRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("accessibility")]
        public AccessibilityAccessibilityData Accessibility { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("isDisabled", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsDisabled { get; set; }

        [JsonProperty("serviceEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public StickyServiceEndpoint ServiceEndpoint { get; set; }
    }

    public partial class ButtonRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("watchEndpoint")]
        public FluffyWatchEndpoint WatchEndpoint { get; set; }
    }

    public partial class FluffyWatchEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class StickyServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("shareEntityServiceEndpoint")]
        public ShareEntityServiceEndpoint ShareEntityServiceEndpoint { get; set; }
    }

    public partial class ShareEntityServiceEndpoint
    {
        [JsonProperty("serializedShareEntity")]
        public string SerializedShareEntity { get; set; }

        [JsonProperty("commands")]
        public List<ShareEntityServiceEndpointCommand> Commands { get; set; }
    }

    public partial class ShareEntityServiceEndpointCommand
    {
        [JsonProperty("openPopupAction")]
        public FluffyOpenPopupAction OpenPopupAction { get; set; }
    }

    public partial class FluffyOpenPopupAction
    {
        [JsonProperty("popup")]
        public FluffyPopup Popup { get; set; }

        [JsonProperty("popupType")]
        public string PopupType { get; set; }

        [JsonProperty("beReused")]
        public bool BeReused { get; set; }
    }

    public partial class FluffyPopup
    {
        [JsonProperty("unifiedSharePanelRenderer")]
        public UnifiedSharePanelRenderer UnifiedSharePanelRenderer { get; set; }
    }

    public partial class UnifiedSharePanelRenderer
    {
        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("showLoadingSpinner")]
        public bool ShowLoadingSpinner { get; set; }
    }

    public partial class ToggleButtonRenderer
    {
        [JsonProperty("style")]
        public StyleClass Style { get; set; }

        [JsonProperty("size")]
        public Size Size { get; set; }

        [JsonProperty("isToggled")]
        public bool IsToggled { get; set; }

        [JsonProperty("isDisabled")]
        public bool IsDisabled { get; set; }

        [JsonProperty("defaultIcon")]
        public IconImage DefaultIcon { get; set; }

        [JsonProperty("defaultServiceEndpoint")]
        public ServiceEndpoint DefaultServiceEndpoint { get; set; }

        [JsonProperty("toggledIcon")]
        public IconImage ToggledIcon { get; set; }

        [JsonProperty("toggledServiceEndpoint")]
        public ServiceEndpoint ToggledServiceEndpoint { get; set; }

        [JsonProperty("accessibility")]
        public AccessibilityAccessibilityData Accessibility { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("defaultTooltip")]
        public string DefaultTooltip { get; set; }

        [JsonProperty("toggledTooltip")]
        public string ToggledTooltip { get; set; }

        [JsonProperty("accessibilityData")]
        public SubscribeAccessibilityClass AccessibilityData { get; set; }

        [JsonProperty("toggledAccessibilityData")]
        public SubscribeAccessibilityClass ToggledAccessibilityData { get; set; }
    }

    public partial class ServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("likeEndpoint")]
        public LikeEndpoint LikeEndpoint { get; set; }
    }

    public partial class LikeEndpoint
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("target")]
        public Target Target { get; set; }
    }

    public partial class Target
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }
    }

    public partial class Size
    {
        [JsonProperty("sizeType")]
        public string SizeType { get; set; }
    }

    public partial class StyleClass
    {
        [JsonProperty("styleType")]
        public string StyleType { get; set; }
    }

    public partial class PlaylistSidebarPrimaryInfoRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("watchEndpoint")]
        public TentacledWatchEndpoint WatchEndpoint { get; set; }
    }

    public partial class TentacledWatchEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }
    }

    public partial class Stat
    {
        [JsonProperty("runs", NullValueHandling = NullValueHandling.Ignore)]
        public List<TextRun> Runs { get; set; }

        [JsonProperty("simpleText", NullValueHandling = NullValueHandling.Ignore)]
        public string SimpleText { get; set; }
    }

    public partial class PlaylistSidebarPrimaryInfoRendererThumbnailOverlay
    {
        [JsonProperty("thumbnailOverlaySidePanelRenderer")]
        public ThumbnailOverlaySidePanelRenderer ThumbnailOverlaySidePanelRenderer { get; set; }
    }

    public partial class ThumbnailOverlaySidePanelRenderer
    {
        [JsonProperty("text")]
        public TextElement Text { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }
    }

    public partial class ThumbnailRenderer
    {
        [JsonProperty("playlistVideoThumbnailRenderer")]
        public PlaylistVideoThumbnailRenderer PlaylistVideoThumbnailRenderer { get; set; }
    }

    public partial class PlaylistVideoThumbnailRenderer
    {
        [JsonProperty("thumbnail")]
        public PlaylistVideoRendererThumbnail Thumbnail { get; set; }
    }

    public partial class PlaylistSidebarPrimaryInfoRendererTitle
    {
        [JsonProperty("runs")]
        public List<PurpleRun> Runs { get; set; }
    }

    public partial class PurpleRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("navigationEndpoint")]
        public PlaylistSidebarPrimaryInfoRendererNavigationEndpoint NavigationEndpoint { get; set; }
    }

    public partial class PlaylistSidebarSecondaryInfoRenderer
    {
        [JsonProperty("videoOwner")]
        public VideoOwner VideoOwner { get; set; }

        [JsonProperty("button")]
        public Button Button { get; set; }
    }

    public partial class Button
    {
        [JsonProperty("subscribeButtonRenderer")]
        public SubscribeButtonRenderer SubscribeButtonRenderer { get; set; }
    }

    public partial class SubscribeButtonRenderer
    {
        [JsonProperty("buttonText")]
        public TextElement ButtonText { get; set; }

        [JsonProperty("subscriberCountText")]
        public ShowMoreText SubscriberCountText { get; set; }

        [JsonProperty("subscribed")]
        public bool Subscribed { get; set; }

        [JsonProperty("enabled")]
        public bool Enabled { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("channelId")]
        public string ChannelId { get; set; }

        [JsonProperty("showPreferences")]
        public bool ShowPreferences { get; set; }

        [JsonProperty("subscriberCountWithUnsubscribeText")]
        public ShowMoreText SubscriberCountWithUnsubscribeText { get; set; }

        [JsonProperty("subscribedButtonText")]
        public TextElement SubscribedButtonText { get; set; }

        [JsonProperty("unsubscribedButtonText")]
        public TextElement UnsubscribedButtonText { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("unsubscribeButtonText")]
        public TextElement UnsubscribeButtonText { get; set; }

        [JsonProperty("longSubscriberCountText")]
        public TextElement LongSubscriberCountText { get; set; }

        [JsonProperty("shortSubscriberCountText")]
        public ShowMoreText ShortSubscriberCountText { get; set; }

        [JsonProperty("subscribeAccessibility")]
        public SubscribeAccessibilityClass SubscribeAccessibility { get; set; }

        [JsonProperty("unsubscribeAccessibility")]
        public SubscribeAccessibilityClass UnsubscribeAccessibility { get; set; }

        [JsonProperty("notificationPreferenceButton")]
        public NotificationPreferenceButton NotificationPreferenceButton { get; set; }

        [JsonProperty("subscribedEntityKey")]
        public string SubscribedEntityKey { get; set; }

        [JsonProperty("onSubscribeEndpoints")]
        public List<OnSubscribeEndpoint> OnSubscribeEndpoints { get; set; }

        [JsonProperty("onUnsubscribeEndpoints")]
        public List<OnUnsubscribeEndpoint> OnUnsubscribeEndpoints { get; set; }
    }

    public partial class NotificationPreferenceButton
    {
        [JsonProperty("subscriptionNotificationToggleButtonRenderer")]
        public SubscriptionNotificationToggleButtonRenderer SubscriptionNotificationToggleButtonRenderer { get; set; }
    }

    public partial class SubscriptionNotificationToggleButtonRenderer
    {
        [JsonProperty("states")]
        public List<StateElement> States { get; set; }

        [JsonProperty("currentStateId")]
        public long CurrentStateId { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("command")]
        public SubscriptionNotificationToggleButtonRendererCommand Command { get; set; }
    }

    public partial class SubscriptionNotificationToggleButtonRendererCommand
    {
        [JsonProperty("commandExecutorCommand")]
        public CommandExecutorCommand CommandExecutorCommand { get; set; }
    }

    public partial class CommandExecutorCommand
    {
        [JsonProperty("commands")]
        public List<CommandExecutorCommandCommand> Commands { get; set; }
    }

    public partial class CommandExecutorCommandCommand
    {
        [JsonProperty("openPopupAction")]
        public TentacledOpenPopupAction OpenPopupAction { get; set; }
    }

    public partial class TentacledOpenPopupAction
    {
        [JsonProperty("popup")]
        public TentacledPopup Popup { get; set; }

        [JsonProperty("popupType")]
        public string PopupType { get; set; }
    }

    public partial class TentacledPopup
    {
        [JsonProperty("menuPopupRenderer")]
        public MenuPopupRenderer MenuPopupRenderer { get; set; }
    }

    public partial class MenuPopupRenderer
    {
        [JsonProperty("items")]
        public List<MenuPopupRendererItem> Items { get; set; }
    }

    public partial class MenuPopupRendererItem
    {
        [JsonProperty("menuServiceItemRenderer")]
        public TentacledMenuServiceItemRenderer MenuServiceItemRenderer { get; set; }
    }

    public partial class TentacledMenuServiceItemRenderer
    {
        [JsonProperty("text")]
        public TextElement Text { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("serviceEndpoint")]
        public IndigoServiceEndpoint ServiceEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("isSelected")]
        public bool IsSelected { get; set; }
    }

    public partial class IndigoServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("modifyChannelNotificationPreferenceEndpoint")]
        public ModifyChannelNotificationPreferenceEndpoint ModifyChannelNotificationPreferenceEndpoint { get; set; }
    }

    public partial class ModifyChannelNotificationPreferenceEndpoint
    {
        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class StateElement
    {
        [JsonProperty("stateId")]
        public long StateId { get; set; }

        [JsonProperty("nextStateId")]
        public long NextStateId { get; set; }

        [JsonProperty("state")]
        public StateState State { get; set; }
    }

    public partial class StateState
    {
        [JsonProperty("buttonRenderer")]
        public StateButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class StateButtonRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("isDisabled")]
        public bool IsDisabled { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("accessibility")]
        public AccessibilityAccessibilityData Accessibility { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("accessibilityData")]
        public SubscribeAccessibilityClass AccessibilityData { get; set; }
    }

    public partial class OnSubscribeEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("subscribeEndpoint")]
        public SubscribeEndpoint SubscribeEndpoint { get; set; }
    }

    public partial class SubscribeEndpoint
    {
        [JsonProperty("channelIds")]
        public List<string> ChannelIds { get; set; }

        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class OnUnsubscribeEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public CommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public OnUnsubscribeEndpointSignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class OnUnsubscribeEndpointSignalServiceEndpoint
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }

        [JsonProperty("actions")]
        public List<IndecentAction> Actions { get; set; }
    }

    public partial class IndecentAction
    {
        [JsonProperty("openPopupAction")]
        public StickyOpenPopupAction OpenPopupAction { get; set; }
    }

    public partial class StickyOpenPopupAction
    {
        [JsonProperty("popup")]
        public StickyPopup Popup { get; set; }

        [JsonProperty("popupType")]
        public string PopupType { get; set; }
    }

    public partial class StickyPopup
    {
        [JsonProperty("confirmDialogRenderer")]
        public FluffyConfirmDialogRenderer ConfirmDialogRenderer { get; set; }
    }

    public partial class FluffyConfirmDialogRenderer
    {
        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("dialogMessages")]
        public List<TextElement> DialogMessages { get; set; }

        [JsonProperty("confirmButton")]
        public PurpleButton ConfirmButton { get; set; }

        [JsonProperty("cancelButton")]
        public PurpleButton CancelButton { get; set; }

        [JsonProperty("primaryIsCancel")]
        public bool PrimaryIsCancel { get; set; }
    }

    public partial class PurpleButton
    {
        [JsonProperty("buttonRenderer")]
        public PurpleButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class PurpleButtonRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("text")]
        public TextElement Text { get; set; }

        [JsonProperty("accessibility")]
        public AccessibilityAccessibilityData Accessibility { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("serviceEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public IndecentServiceEndpoint ServiceEndpoint { get; set; }
    }

    public partial class IndecentServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("unsubscribeEndpoint")]
        public SubscribeEndpoint UnsubscribeEndpoint { get; set; }
    }

    public partial class VideoOwner
    {
        [JsonProperty("videoOwnerRenderer")]
        public VideoOwnerRenderer VideoOwnerRenderer { get; set; }
    }

    public partial class VideoOwnerRenderer
    {
        [JsonProperty("thumbnail")]
        public PlaylistVideoRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("title")]
        public ShortBylineTextClass Title { get; set; }

        [JsonProperty("navigationEndpoint")]
        public VideoOwnerRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class VideoOwnerRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("browseEndpoint")]
        public PurpleBrowseEndpoint BrowseEndpoint { get; set; }
    }

    public partial class PurpleBrowseEndpoint
    {
        [JsonProperty("browseId")]
        public string BrowseId { get; set; }

        [JsonProperty("canonicalBaseUrl")]
        public string CanonicalBaseUrl { get; set; }
    }

    public partial class Topbar
    {
        [JsonProperty("desktopTopbarRenderer")]
        public DesktopTopbarRenderer DesktopTopbarRenderer { get; set; }
    }

    public partial class DesktopTopbarRenderer
    {
        [JsonProperty("logo")]
        public Logo Logo { get; set; }

        [JsonProperty("searchbox")]
        public Searchbox Searchbox { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("countryCode")]
        public string CountryCode { get; set; }

        [JsonProperty("topbarButtons")]
        public List<TopbarButton> TopbarButtons { get; set; }

        [JsonProperty("hotkeyDialog")]
        public HotkeyDialog HotkeyDialog { get; set; }

        [JsonProperty("backButton")]
        public BackButtonClass BackButton { get; set; }

        [JsonProperty("forwardButton")]
        public BackButtonClass ForwardButton { get; set; }

        [JsonProperty("a11ySkipNavigationButton")]
        public A11YSkipNavigationButton A11YSkipNavigationButton { get; set; }
    }

    public partial class A11YSkipNavigationButton
    {
        [JsonProperty("buttonRenderer")]
        public A11YSkipNavigationButtonButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class A11YSkipNavigationButtonButtonRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("isDisabled")]
        public bool IsDisabled { get; set; }

        [JsonProperty("text")]
        public TextElement Text { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("command")]
        public ButtonRendererCommand Command { get; set; }
    }

    public partial class BackButtonClass
    {
        [JsonProperty("buttonRenderer")]
        public BackButtonButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class BackButtonButtonRenderer
    {
        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("command")]
        public ButtonRendererCommand Command { get; set; }
    }

    public partial class HotkeyDialog
    {
        [JsonProperty("hotkeyDialogRenderer")]
        public HotkeyDialogRenderer HotkeyDialogRenderer { get; set; }
    }

    public partial class HotkeyDialogRenderer
    {
        [JsonProperty("title")]
        public TextElement Title { get; set; }

        [JsonProperty("sections")]
        public List<HotkeyDialogRendererSection> Sections { get; set; }

        [JsonProperty("dismissButton")]
        public DismissButtonClass DismissButton { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class HotkeyDialogRendererSection
    {
        [JsonProperty("hotkeyDialogSectionRenderer")]
        public HotkeyDialogSectionRenderer HotkeyDialogSectionRenderer { get; set; }
    }

    public partial class HotkeyDialogSectionRenderer
    {
        [JsonProperty("title")]
        public TextElement Title { get; set; }

        [JsonProperty("options")]
        public List<Option> Options { get; set; }
    }

    public partial class Option
    {
        [JsonProperty("hotkeyDialogSectionOptionRenderer")]
        public HotkeyDialogSectionOptionRenderer HotkeyDialogSectionOptionRenderer { get; set; }
    }

    public partial class HotkeyDialogSectionOptionRenderer
    {
        [JsonProperty("label")]
        public TextElement Label { get; set; }

        [JsonProperty("hotkey")]
        public string Hotkey { get; set; }

        [JsonProperty("hotkeyAccessibilityLabel", NullValueHandling = NullValueHandling.Ignore)]
        public SubscribeAccessibilityClass HotkeyAccessibilityLabel { get; set; }
    }

    public partial class Logo
    {
        [JsonProperty("topbarLogoRenderer")]
        public TopbarLogoRenderer TopbarLogoRenderer { get; set; }
    }

    public partial class TopbarLogoRenderer
    {
        [JsonProperty("iconImage")]
        public IconImage IconImage { get; set; }

        [JsonProperty("tooltipText")]
        public TextElement TooltipText { get; set; }

        [JsonProperty("endpoint")]
        public Endpoint Endpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class Searchbox
    {
        [JsonProperty("fusionSearchboxRenderer")]
        public FusionSearchboxRenderer FusionSearchboxRenderer { get; set; }
    }

    public partial class FusionSearchboxRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("placeholderText")]
        public TextElement PlaceholderText { get; set; }

        [JsonProperty("config")]
        public Config Config { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("searchEndpoint")]
        public FusionSearchboxRendererSearchEndpoint SearchEndpoint { get; set; }
    }

    public partial class Config
    {
        [JsonProperty("webSearchboxConfig")]
        public WebSearchboxConfig WebSearchboxConfig { get; set; }
    }

    public partial class WebSearchboxConfig
    {
        [JsonProperty("requestLanguage")]
        public string RequestLanguage { get; set; }

        [JsonProperty("requestDomain")]
        public string RequestDomain { get; set; }

        [JsonProperty("hasOnscreenKeyboard")]
        public bool HasOnscreenKeyboard { get; set; }

        [JsonProperty("focusSearchbox")]
        public bool FocusSearchbox { get; set; }
    }

    public partial class FusionSearchboxRendererSearchEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("searchEndpoint")]
        public SearchEndpointSearchEndpoint SearchEndpoint { get; set; }
    }

    public partial class SearchEndpointSearchEndpoint
    {
        [JsonProperty("query")]
        public string Query { get; set; }
    }

    public partial class TopbarButton
    {
        [JsonProperty("topbarMenuButtonRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public TopbarMenuButtonRenderer TopbarMenuButtonRenderer { get; set; }

        [JsonProperty("notificationTopbarButtonRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public NotificationTopbarButtonRenderer NotificationTopbarButtonRenderer { get; set; }
    }

    public partial class NotificationTopbarButtonRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("menuRequest")]
        public MenuRequest MenuRequest { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("accessibility")]
        public SubscribeAccessibilityClass Accessibility { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("updateUnseenCountEndpoint")]
        public UpdateUnseenCountEndpoint UpdateUnseenCountEndpoint { get; set; }

        [JsonProperty("notificationCount")]
        public long NotificationCount { get; set; }

        [JsonProperty("handlerDatas")]
        public List<string> HandlerDatas { get; set; }
    }

    public partial class MenuRequest
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public MenuRequestSignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class MenuRequestSignalServiceEndpoint
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }

        [JsonProperty("actions")]
        public List<HilariousAction> Actions { get; set; }
    }

    public partial class HilariousAction
    {
        [JsonProperty("openPopupAction")]
        public IndigoOpenPopupAction OpenPopupAction { get; set; }
    }

    public partial class IndigoOpenPopupAction
    {
        [JsonProperty("popup")]
        public IndigoPopup Popup { get; set; }

        [JsonProperty("popupType")]
        public string PopupType { get; set; }

        [JsonProperty("beReused")]
        public bool BeReused { get; set; }
    }

    public partial class IndigoPopup
    {
        [JsonProperty("multiPageMenuRenderer")]
        public PopupMultiPageMenuRenderer MultiPageMenuRenderer { get; set; }
    }

    public partial class PopupMultiPageMenuRenderer
    {
        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("showLoadingSpinner")]
        public bool ShowLoadingSpinner { get; set; }
    }

    public partial class UpdateUnseenCountEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public OnCreateListCommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public Signal SignalServiceEndpoint { get; set; }
    }

    public partial class TopbarMenuButtonRenderer
    {
        [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
        public IconImage Icon { get; set; }

        [JsonProperty("menuRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public TopbarMenuButtonRendererMenuRenderer MenuRenderer { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("accessibility")]
        public SubscribeAccessibilityClass Accessibility { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("style", NullValueHandling = NullValueHandling.Ignore)]
        public string Style { get; set; }

        [JsonProperty("avatar", NullValueHandling = NullValueHandling.Ignore)]
        public Avatar Avatar { get; set; }

        [JsonProperty("menuRequest", NullValueHandling = NullValueHandling.Ignore)]
        public MenuRequest MenuRequest { get; set; }
    }

    public partial class Avatar
    {
        [JsonProperty("thumbnails")]
        public List<ThumbnailElement> Thumbnails { get; set; }

        [JsonProperty("accessibility")]
        public SubscribeAccessibilityClass Accessibility { get; set; }

        [JsonProperty("webThumbnailDetailsExtensionData")]
        public WebThumbnailDetailsExtensionData WebThumbnailDetailsExtensionData { get; set; }
    }

    public partial class WebThumbnailDetailsExtensionData
    {
        [JsonProperty("excludeFromVpl")]
        public bool ExcludeFromVpl { get; set; }
    }

    public partial class TopbarMenuButtonRendererMenuRenderer
    {
        [JsonProperty("multiPageMenuRenderer")]
        public MenuRendererMultiPageMenuRenderer MultiPageMenuRenderer { get; set; }
    }

    public partial class MenuRendererMultiPageMenuRenderer
    {
        [JsonProperty("sections")]
        public List<MultiPageMenuRendererSection> Sections { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("style", NullValueHandling = NullValueHandling.Ignore)]
        public string Style { get; set; }
    }

    public partial class MultiPageMenuRendererSection
    {
        [JsonProperty("multiPageMenuSectionRenderer")]
        public MultiPageMenuSectionRenderer MultiPageMenuSectionRenderer { get; set; }
    }

    public partial class MultiPageMenuSectionRenderer
    {
        [JsonProperty("items")]
        public List<MultiPageMenuSectionRendererItem> Items { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class MultiPageMenuSectionRendererItem
    {
        [JsonProperty("compactLinkRenderer")]
        public CompactLinkRenderer CompactLinkRenderer { get; set; }
    }

    public partial class CompactLinkRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("title")]
        public TextElement Title { get; set; }

        [JsonProperty("navigationEndpoint")]
        public CompactLinkRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("style", NullValueHandling = NullValueHandling.Ignore)]
        public string Style { get; set; }
    }

    public partial class CompactLinkRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("uploadEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public UploadEndpoint UploadEndpoint { get; set; }

        [JsonProperty("signalNavigationEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public Signal SignalNavigationEndpoint { get; set; }

        [JsonProperty("urlEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public UrlEndpoint UrlEndpoint { get; set; }
    }

    public partial class UploadEndpoint
    {
        [JsonProperty("hack")]
        public bool Hack { get; set; }
    }

    public partial class UrlEndpoint
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("target")]
        public string Target { get; set; }
    }

   

    
}
