// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ObjModel;
//
//    var temperatures = Temperatures.FromJson(jsonString);

namespace YoutubeAPI.Models.Basic
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;


    public partial class Temperatures
    {
        [JsonProperty("responseContext")]
        public ResponseContext ResponseContext { get; set; }

        [JsonProperty("estimatedResults")]
        public long EstimatedResults { get; set; }

        [JsonProperty("contents")]
        public Contents Contents { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("topbar")]
        public Topbar Topbar { get; set; }

        [JsonProperty("adSafetyReason")]
        public AdSafetyReason AdSafetyReason { get; set; }

        [JsonProperty("refinements")]
        public List<string> Refinements { get; set; }
    }

    public partial class AdSafetyReason
    {
        [JsonProperty("apmUserPreference")]
        public ApmUserPreference ApmUserPreference { get; set; }

        [JsonProperty("isWebAndAppActivityEnabled")]
        public bool IsWebAndAppActivityEnabled { get; set; }
    }

    public partial class ApmUserPreference
    {
        [JsonProperty("adsPersonalizationOptout")]
        public bool AdsPersonalizationOptout { get; set; }
    }

    public partial class Contents
    {
        [JsonProperty("twoColumnSearchResultsRenderer")]
        public TwoColumnSearchResultsRenderer TwoColumnSearchResultsRenderer { get; set; }

        [JsonProperty("twoColumnBrowseResultsRenderer")]
        public TwoColumnBrowseResultsRenderer TwoColumnBrowseResultsRenderer { get; set; }
    }

    public partial class TwoColumnBrowseResultsRenderer
    {
        

        [JsonProperty("tabs")]
        public List<TabItem> Tabs { get; set; }

    }

    public partial class TwoColumnSearchResultsRenderer
    {
        [JsonProperty("primaryContents")]
        public PrimaryContents PrimaryContents { get; set; }

       

    }

    public partial class TabItem
    {
        [JsonProperty("tabRenderer")]
        public TabRenderer TabRenderer { get; set; }
    }

    public partial class TabRenderer
    {
        [JsonProperty("content")]
        public TabContent Content { get; set; }
    }

    public partial class TabContent
    {
        [JsonProperty("richGridRenderer")]
        public RichGridRenderer RichGridRenderer { get; set; }
    }

    public partial class RichGridRenderer
    {
        [JsonProperty("contents")]
        public List<ItemTabContent> Contents { get; set; }
    }

    public partial class ItemTabContent
    {
        [JsonProperty("richItemRenderer")]
        public RichItemRenderer RichItemRenderer { get; set; }
    }

    public partial class RichItemRenderer
    {
        [JsonProperty("content")]
        public RichItemContent Content { get; set; }
    }

    public partial class RichItemContent
    {
        
        [JsonProperty("videoRenderer")]
        public ItemVideoRenderer VideoRenderer { get; set; }
    }

    public partial class PrimaryContents
    {
        [JsonProperty("sectionListRenderer")]
        public SectionListRenderer SectionListRenderer1 { get; set; }
        [JsonProperty("richGridRenderer")]
        public SectionListRenderer SectionListRenderer2 { get; set; }
    }

    public partial class SectionListRenderer
    {
        [JsonProperty("contents")]
        public List<SectionListRendererContent> Contents { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("subMenu")]
        public SubMenu SubMenu { get; set; }

        [JsonProperty("hideBottomSeparator")]
        public bool HideBottomSeparator { get; set; }

        [JsonProperty("targetId")]
        public string TargetId { get; set; }
    }

    public partial class SectionListRendererContent
    {
        [JsonProperty("itemSectionRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ItemSectionRenderer ItemSectionRenderer1 { get; set; }

        [JsonProperty("richGridRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ItemSectionRenderer ItemSectionRenderer2 { get; set; }

        [JsonProperty("continuationItemRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ContinuationItemRenderer ContinuationItemRenderer { get; set; }
    }

    public partial class ContinuationItemRenderer
    {
        [JsonProperty("trigger")]
        public string Trigger { get; set; }

        [JsonProperty("continuationEndpoint")]
        public ContinuationEndpoint ContinuationEndpoint { get; set; }
    }

    public partial class ContinuationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("continuationCommand")]
        public ContinuationCommand ContinuationCommand { get; set; }
    }

    public partial class ContinuationEndpointCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public PurpleWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class PurpleWebCommandMetadata
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("sendPost")]
        public bool SendPost { get; set; }

        [JsonProperty("apiUrl", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string ApiUrl { get; set; }
    }

    public partial class ContinuationCommand
    {
        [JsonProperty("token")]
        public string Token { get; set; }

        [JsonProperty("request")]
        public string Request { get; set; }
    }

    public partial class ItemSectionRenderer
    {
        [JsonProperty("contents")]
        public List<ItemSectionRendererContent> Contents { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        //[JsonProperty("content")]
        //public ContentData ContentData { get; set; }
    }

    //public partial class ContentData
    //{
    //    [JsonProperty("videoRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    //    public ContentVideoRenderer VideoRenderer { get; set; }
    //}

    public partial class ItemSectionRendererContent
    {
        [JsonProperty("radioRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public RadioRenderer RadioRenderer { get; set; }

        [JsonProperty("videoRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ContentVideoRenderer VideoRenderer { get; set; }

        [JsonProperty("richItemRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public RichItemRenderer RichRenderer { get; set; }

        [JsonProperty("shelfRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ShelfRenderer ShelfRenderer { get; set; }

        [JsonProperty("horizontalCardListRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public HorizontalCardListRenderer HorizontalCardListRenderer { get; set; }
    }

    public partial class HorizontalCardListRenderer
    {
        [JsonProperty("cards")]
        public List<Card> Cards { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("header")]
        public Header Header { get; set; }

        [JsonProperty("style")]
        public HorizontalCardListRendererStyle Style { get; set; }
    }

    public partial class Card
    {
        [JsonProperty("searchRefinementCardRenderer")]
        public SearchRefinementCardRenderer SearchRefinementCardRenderer { get; set; }
    }

    public partial class SearchRefinementCardRenderer
    {
        [JsonProperty("thumbnail")]
        public SearchRefinementCardRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("query")]
        public TitleClass Query { get; set; }

        [JsonProperty("searchEndpoint")]
        public Endpoint SearchEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class TitleClass
    {
        [JsonProperty("runs")]
        public List<TextRun> Runs { get; set; }
    }

    public partial class TextRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class Endpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("searchEndpoint")]
        public NavigationEndpointSearchEndpoint SearchEndpoint { get; set; }
    }

    public partial class NavigationEndpointCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public FluffyWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class FluffyWebCommandMetadata
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("webPageType")]
        public string WebPageType { get; set; }

        [JsonProperty("rootVe")]
        public long RootVe { get; set; }
    }

    public partial class NavigationEndpointSearchEndpoint
    {
        [JsonProperty("query")]
        public string Query { get; set; }

        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class SearchRefinementCardRendererThumbnail
    {
        [JsonProperty("thumbnails")]
        public List<ThumbnailElement> Thumbnails { get; set; }
    }

    public partial class ThumbnailElement
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }
    }

    public partial class Header
    {
        [JsonProperty("richListHeaderRenderer")]
        public RichListHeaderRenderer RichListHeaderRenderer { get; set; }
    }

    public partial class RichListHeaderRenderer
    {
        [JsonProperty("title")]
        public ThumbnailText Title { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }
    }

    public partial class IconImage
    {
        [JsonProperty("iconType")]
        public string IconType { get; set; }
    }

    public partial class ThumbnailText
    {
        [JsonProperty("runs")]
        public List<ThumbnailTextRun> Runs { get; set; }
    }

    public partial class ThumbnailTextRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("bold", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public bool? Bold { get; set; }
    }

    public partial class HorizontalCardListRendererStyle
    {
        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class RadioRenderer
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("title")]
        public LongBylineTextClass Title { get; set; }

        [JsonProperty("thumbnail")]
        public SearchRefinementCardRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("videoCountText")]
        public TitleClass VideoCountText { get; set; }

        [JsonProperty("navigationEndpoint")]
        public RadioRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("shortBylineText")]
        public LongBylineTextClass ShortBylineText { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("videos")]
        public List<Video> Videos { get; set; }

        [JsonProperty("thumbnailText")]
        public ThumbnailText ThumbnailText { get; set; }

        [JsonProperty("longBylineText")]
        public LongBylineTextClass LongBylineText { get; set; }

        [JsonProperty("thumbnailOverlays")]
        public List<RadioRendererThumbnailOverlay> ThumbnailOverlays { get; set; }

        [JsonProperty("videoCountShortText")]
        public TitleClass VideoCountShortText { get; set; }
    }

    public partial class LongBylineTextClass
    {
        [JsonProperty("simpleText")]
        public string SimpleText { get; set; }
    }

    public partial class RadioRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("watchEndpoint")]
        public PurpleWatchEndpoint WatchEndpoint { get; set; }
    }

    public partial class PurpleWatchEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("params")]
        public string Params { get; set; }

        [JsonProperty("continuePlayback", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public bool? ContinuePlayback { get; set; }
    }

    public partial class RadioRendererThumbnailOverlay
    {
        [JsonProperty("thumbnailOverlaySidePanelRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayRenderer ThumbnailOverlaySidePanelRenderer { get; set; }

        [JsonProperty("thumbnailOverlayHoverTextRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayRenderer ThumbnailOverlayHoverTextRenderer { get; set; }

        [JsonProperty("thumbnailOverlayNowPlayingRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayNowPlayingRenderer ThumbnailOverlayNowPlayingRenderer { get; set; }
    }

    public partial class ThumbnailOverlayRenderer
    {
        [JsonProperty("text")]
        public TitleClass Text { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }
    }

    public partial class ThumbnailOverlayNowPlayingRenderer
    {
        [JsonProperty("text")]
        public TitleClass Text { get; set; }
    }

    public partial class Video
    {
        [JsonProperty("childVideoRenderer")]
        public ChildVideoRenderer ChildVideoRenderer { get; set; }
    }

    public partial class ChildVideoRenderer
    {
        [JsonProperty("title")]
        public LongBylineTextClass Title { get; set; }

        [JsonProperty("navigationEndpoint")]
        public RadioRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("lengthText")]
        public LengthTextClass LengthText { get; set; }

        [JsonProperty("videoId")]
        public string VideoId { get; set; }
    }

    public partial class LengthTextClass
    {
        [JsonProperty("accessibility")]
        public HotkeyAccessibilityLabelClass Accessibility { get; set; }

        [JsonProperty("simpleText")]
        public string SimpleText { get; set; }
    }

    public partial class HotkeyAccessibilityLabelClass
    {
        [JsonProperty("accessibilityData")]
        public AccessibilityAccessibilityData AccessibilityData { get; set; }
    }

    public partial class AccessibilityAccessibilityData
    {
        [JsonProperty("label")]
        public string Label { get; set; }
    }

    public partial class ShelfRenderer
    {
        [JsonProperty("title")]
        public LongBylineTextClass Title { get; set; }

        [JsonProperty("content")]
        public ShelfRendererContent Content { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class ShelfRendererContent
    {
        [JsonProperty("verticalListRenderer")]
        public VerticalListRenderer VerticalListRenderer { get; set; }
    }

    public partial class VerticalListRenderer
    {
        [JsonProperty("items")]
        public List<VerticalListRendererItem> Items { get; set; }

        [JsonProperty("collapsedItemCount")]
        public long CollapsedItemCount { get; set; }

        [JsonProperty("collapsedStateButtonText")]
        public CollapsedStateButtonTextClass CollapsedStateButtonText { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class CollapsedStateButtonTextClass
    {
        [JsonProperty("runs")]
        public List<TextRun> Runs { get; set; }

        [JsonProperty("accessibility")]
        public HotkeyAccessibilityLabelClass Accessibility { get; set; }
    }

    public partial class VerticalListRendererItem
    {
        [JsonProperty("videoRenderer")]
        public ItemVideoRenderer VideoRenderer { get; set; }
    }

    public partial class ItemVideoRenderer
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("thumbnail")]
        public SearchRefinementCardRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("title")]
        public CollapsedStateButtonTextClass Title { get; set; }

        [JsonProperty("descriptionSnippet")]
        public ThumbnailText DescriptionSnippet { get; set; }

        [JsonProperty("longBylineText")]
        public Text LongBylineText { get; set; }

        [JsonProperty("publishedTimeText")]
        public LongBylineTextClass PublishedTimeText { get; set; }

        [JsonProperty("lengthText")]
        public LengthTextClass LengthText { get; set; }

        [JsonProperty("viewCountText")]
        public LongBylineTextClass ViewCountText { get; set; }

        [JsonProperty("navigationEndpoint")]
        public VideoRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("badges", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public List<Badge> Badges { get; set; }

        [JsonProperty("ownerText")]
        public Text OwnerText { get; set; }

        [JsonProperty("shortBylineText")]
        public Text ShortBylineText { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("showActionMenu")]
        public bool ShowActionMenu { get; set; }

        [JsonProperty("shortViewCountText")]
        public LongBylineTextClass ShortViewCountText { get; set; }

        [JsonProperty("isWatched", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsWatched { get; set; }

        [JsonProperty("menu")]
        public Menu Menu { get; set; }

        [JsonProperty("channelThumbnailSupportedRenderers")]
        public ChannelThumbnailSupportedRenderers ChannelThumbnailSupportedRenderers { get; set; }

        [JsonProperty("thumbnailOverlays")]
        public List<VideoRendererThumbnailOverlay> ThumbnailOverlays { get; set; }

        [JsonProperty("richThumbnail", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public RichThumbnail RichThumbnail { get; set; }

        [JsonProperty("ownerBadges", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public List<OwnerBadge> OwnerBadges { get; set; }
    }

    public partial class Badge
    {
        [JsonProperty("metadataBadgeRenderer")]
        public BadgeMetadataBadgeRenderer MetadataBadgeRenderer { get; set; }
    }

    public partial class BadgeMetadataBadgeRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class ChannelThumbnailSupportedRenderers
    {
        [JsonProperty("channelThumbnailWithLinkRenderer")]
        public ChannelThumbnailWithLinkRenderer ChannelThumbnailWithLinkRenderer { get; set; }
    }

    public partial class ChannelThumbnailWithLinkRenderer
    {
        [JsonProperty("thumbnail")]
        public SearchRefinementCardRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("navigationEndpoint")]
        public ChannelThumbnailWithLinkRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("accessibility")]
        public HotkeyAccessibilityLabelClass Accessibility { get; set; }
    }

    public partial class ChannelThumbnailWithLinkRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("browseEndpoint")]
        public NavigationEndpointBrowseEndpoint BrowseEndpoint { get; set; }
    }

    public partial class NavigationEndpointBrowseEndpoint
    {
        [JsonProperty("browseId")]
        public string BrowseId { get; set; }

        [JsonProperty("canonicalBaseUrl", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string CanonicalBaseUrl { get; set; }
    }

    public partial class Text
    {
        [JsonProperty("runs")]
        public List<LongBylineTextRun> Runs { get; set; }
    }

    public partial class LongBylineTextRun
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("navigationEndpoint")]
        public ChannelThumbnailWithLinkRendererNavigationEndpoint NavigationEndpoint { get; set; }
    }

    public partial class Menu
    {
        [JsonProperty("menuRenderer")]
        public MenuMenuRenderer MenuRenderer { get; set; }
    }

    public partial class MenuMenuRenderer
    {
        [JsonProperty("items")]
        public List<MenuRendererItem> Items { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("accessibility")]
        public HotkeyAccessibilityLabelClass Accessibility { get; set; }
    }

    public partial class MenuRendererItem
    {
        [JsonProperty("menuServiceItemRenderer")]
        public MenuServiceItemRenderer MenuServiceItemRenderer { get; set; }
    }

    public partial class MenuServiceItemRenderer
    {
        [JsonProperty("text")]
        public TitleClass Text { get; set; }

        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("serviceEndpoint")]
        public ServiceEndpoint ServiceEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("hasSeparator", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public bool? HasSeparator { get; set; }
    }

    public partial class ServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ServiceEndpointSignalServiceEndpoint SignalServiceEndpoint { get; set; }

        [JsonProperty("playlistEditEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ServiceEndpointPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }

        [JsonProperty("addToPlaylistServiceEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public AddToPlaylistServiceEndpoint AddToPlaylistServiceEndpoint { get; set; }

        [JsonProperty("getReportFormEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public GetReportFormEndpoint GetReportFormEndpoint { get; set; }
    }

    public partial class AddToPlaylistServiceEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }
    }

    public partial class GetReportFormEndpoint
    {
        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class ServiceEndpointPlaylistEditEndpoint
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("actions")]
        public List<PurpleAction> Actions { get; set; }
    }

    public partial class PurpleAction
    {
        [JsonProperty("addedVideoId")]
        public string AddedVideoId { get; set; }

        [JsonProperty("action")]
        public string Action { get; set; }
    }

    public partial class ServiceEndpointSignalServiceEndpoint
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }

        [JsonProperty("actions")]
        public List<FluffyAction> Actions { get; set; }
    }

    public partial class FluffyAction
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("addToPlaylistCommand")]
        public AddToPlaylistCommand AddToPlaylistCommand { get; set; }
    }

    public partial class AddToPlaylistCommand
    {
        [JsonProperty("openMiniplayer")]
        public bool OpenMiniplayer { get; set; }

        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("listType")]
        public string ListType { get; set; }

        [JsonProperty("onCreateListCommand")]
        public OnCreateListCommand OnCreateListCommand { get; set; }

        [JsonProperty("videoIds")]
        public List<string> VideoIds { get; set; }
    }

    public partial class OnCreateListCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("createPlaylistServiceEndpoint")]
        public CreatePlaylistServiceEndpoint CreatePlaylistServiceEndpoint { get; set; }
    }

    public partial class CreatePlaylistServiceEndpoint
    {
        [JsonProperty("videoIds")]
        public List<string> VideoIds { get; set; }

        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class VideoRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("watchEndpoint")]
        public FluffyWatchEndpoint WatchEndpoint { get; set; }
    }

    public partial class FluffyWatchEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("startTimeSeconds", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public long? StartTimeSeconds { get; set; }
    }

    public partial class OwnerBadge
    {
        [JsonProperty("metadataBadgeRenderer")]
        public OwnerBadgeMetadataBadgeRenderer MetadataBadgeRenderer { get; set; }
    }

    public partial class OwnerBadgeMetadataBadgeRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class RichThumbnail
    {
        [JsonProperty("movingThumbnailRenderer")]
        public MovingThumbnailRenderer MovingThumbnailRenderer { get; set; }
    }

    public partial class MovingThumbnailRenderer
    {
        [JsonProperty("movingThumbnailDetails")]
        public MovingThumbnailDetails MovingThumbnailDetails { get; set; }

        [JsonProperty("enableHoveredLogging")]
        public bool EnableHoveredLogging { get; set; }

        [JsonProperty("enableOverlay")]
        public bool EnableOverlay { get; set; }
    }

    public partial class MovingThumbnailDetails
    {
        [JsonProperty("thumbnails")]
        public List<ThumbnailElement> Thumbnails { get; set; }

        [JsonProperty("logAsMovingThumbnail")]
        public bool LogAsMovingThumbnail { get; set; }
    }

    public partial class VideoRendererThumbnailOverlay
    {
        [JsonProperty("thumbnailOverlayResumePlaybackRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayResumePlaybackRenderer ThumbnailOverlayResumePlaybackRenderer { get; set; }

        [JsonProperty("thumbnailOverlayTimeStatusRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayTimeStatusRenderer ThumbnailOverlayTimeStatusRenderer { get; set; }

        [JsonProperty("thumbnailOverlayToggleButtonRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayToggleButtonRenderer ThumbnailOverlayToggleButtonRenderer { get; set; }

        [JsonProperty("thumbnailOverlayNowPlayingRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ThumbnailOverlayNowPlayingRenderer ThumbnailOverlayNowPlayingRenderer { get; set; }
    }

    public partial class ThumbnailOverlayResumePlaybackRenderer
    {
        [JsonProperty("percentDurationWatched")]
        public long PercentDurationWatched { get; set; }
    }

    public partial class ThumbnailOverlayTimeStatusRenderer
    {
        [JsonProperty("text")]
        public LengthTextClass Text { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }
    }

    public partial class ThumbnailOverlayToggleButtonRenderer
    {
        [JsonProperty("isToggled", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsToggled { get; set; }

        [JsonProperty("untoggledIcon")]
        public IconImage UntoggledIcon { get; set; }

        [JsonProperty("toggledIcon")]
        public IconImage ToggledIcon { get; set; }

        [JsonProperty("untoggledTooltip")]
        public string UntoggledTooltip { get; set; }

        [JsonProperty("toggledTooltip")]
        public string ToggledTooltip { get; set; }

        [JsonProperty("untoggledServiceEndpoint")]
        public UntoggledServiceEndpoint UntoggledServiceEndpoint { get; set; }

        [JsonProperty("toggledServiceEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ToggledServiceEndpoint ToggledServiceEndpoint { get; set; }

        [JsonProperty("untoggledAccessibility")]
        public HotkeyAccessibilityLabelClass UntoggledAccessibility { get; set; }

        [JsonProperty("toggledAccessibility")]
        public HotkeyAccessibilityLabelClass ToggledAccessibility { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class ToggledServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("playlistEditEndpoint")]
        public ToggledServiceEndpointPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }
    }

    public partial class ToggledServiceEndpointPlaylistEditEndpoint
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("actions")]
        public List<TentacledAction> Actions { get; set; }
    }

    public partial class TentacledAction
    {
        [JsonProperty("action")]
        public string Action { get; set; }

        [JsonProperty("removedVideoId")]
        public string RemovedVideoId { get; set; }
    }

    public partial class UntoggledServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("playlistEditEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ServiceEndpointPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }

        [JsonProperty("signalServiceEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public ServiceEndpointSignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class ContentVideoRenderer
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("thumbnail")]
        public SearchRefinementCardRendererThumbnail Thumbnail { get; set; }

        [JsonProperty("title")]
        public CollapsedStateButtonTextClass Title { get; set; }

        [JsonProperty("descriptionSnippet")]
        public ThumbnailText DescriptionSnippet { get; set; }

        [JsonProperty("longBylineText")]
        public Text LongBylineText { get; set; }

        [JsonProperty("viewCountText")]
        public ViewCountText ViewCountText { get; set; }

        [JsonProperty("navigationEndpoint")]
        public VideoRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("badges", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public List<Badge> Badges { get; set; }

        [JsonProperty("ownerBadges", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public List<OwnerBadge> OwnerBadges { get; set; }

        [JsonProperty("ownerText")]
        public Text OwnerText { get; set; }

        [JsonProperty("shortBylineText")]
        public Text ShortBylineText { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("showActionMenu")]
        public bool ShowActionMenu { get; set; }

        [JsonProperty("shortViewCountText")]
        public ViewCountText ShortViewCountText { get; set; }

        [JsonProperty("menu")]
        public Menu Menu { get; set; }

        [JsonProperty("channelThumbnailSupportedRenderers")]
        public ChannelThumbnailSupportedRenderers ChannelThumbnailSupportedRenderers { get; set; }

        [JsonProperty("thumbnailOverlays")]
        public List<VideoRendererThumbnailOverlay> ThumbnailOverlays { get; set; }

        [JsonProperty("publishedTimeText", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public LongBylineTextClass PublishedTimeText { get; set; }

        [JsonProperty("lengthText", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public LengthTextClass LengthText { get; set; }

        [JsonProperty("isWatched", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsWatched { get; set; }

        [JsonProperty("richThumbnail", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public RichThumbnail RichThumbnail { get; set; }
    }

    public partial class ViewCountText
    {
        [JsonProperty("runs", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public List<TextRun> Runs { get; set; }

        [JsonProperty("simpleText", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string SimpleText { get; set; }
    }

    public partial class SubMenu
    {
        [JsonProperty("searchSubMenuRenderer")]
        public SearchSubMenuRenderer SearchSubMenuRenderer { get; set; }
    }

    public partial class SearchSubMenuRenderer
    {
        [JsonProperty("title")]
        public TitleClass Title { get; set; }

        [JsonProperty("groups")]
        public List<Group> Groups { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("button")]
        public Button Button { get; set; }
    }

    public partial class Button
    {
        [JsonProperty("toggleButtonRenderer")]
        public ToggleButtonRenderer ToggleButtonRenderer { get; set; }
    }

    public partial class ToggleButtonRenderer
    {
        [JsonProperty("style")]
        public ToggledStyleClass Style { get; set; }

        [JsonProperty("isToggled")]
        public bool IsToggled { get; set; }

        [JsonProperty("isDisabled")]
        public bool IsDisabled { get; set; }

        [JsonProperty("defaultIcon")]
        public IconImage DefaultIcon { get; set; }

        [JsonProperty("defaultText")]
        public TitleClass DefaultText { get; set; }

        [JsonProperty("accessibility")]
        public AccessibilityAccessibilityData Accessibility { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("defaultTooltip")]
        public string DefaultTooltip { get; set; }

        [JsonProperty("toggledTooltip")]
        public string ToggledTooltip { get; set; }

        [JsonProperty("toggledStyle")]
        public ToggledStyleClass ToggledStyle { get; set; }

        [JsonProperty("accessibilityData")]
        public HotkeyAccessibilityLabelClass AccessibilityData { get; set; }
    }

    public partial class ToggledStyleClass
    {
        [JsonProperty("styleType")]
        public string StyleType { get; set; }
    }

    public partial class Group
    {
        [JsonProperty("searchFilterGroupRenderer")]
        public SearchFilterGroupRenderer SearchFilterGroupRenderer { get; set; }
    }

    public partial class SearchFilterGroupRenderer
    {
        [JsonProperty("title")]
        public LongBylineTextClass Title { get; set; }

        [JsonProperty("filters")]
        public List<Filter> Filters { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class Filter
    {
        [JsonProperty("searchFilterRenderer")]
        public SearchFilterRenderer SearchFilterRenderer { get; set; }
    }

    public partial class SearchFilterRenderer
    {
        [JsonProperty("label")]
        public LongBylineTextClass Label { get; set; }

        [JsonProperty("navigationEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public Endpoint NavigationEndpoint { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("status", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }
    }

    public partial class ResponseContext
    {
        [JsonProperty("serviceTrackingParams")]
        public List<ServiceTrackingParam> ServiceTrackingParams { get; set; }

        [JsonProperty("webResponseContextExtensionData")]
        public WebResponseContextExtensionData WebResponseContextExtensionData { get; set; }
    }

    public partial class ServiceTrackingParam
    {
        [JsonProperty("service")]
        public string Service { get; set; }

        [JsonProperty("params")]
        public List<Param> Params { get; set; }
    }

    public partial class Param
    {
        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }
    }

    public partial class WebResponseContextExtensionData
    {
        [JsonProperty("ytConfigData")]
        public YtConfigData YtConfigData { get; set; }

        [JsonProperty("hasDecorated")]
        public bool HasDecorated { get; set; }
    }

    public partial class YtConfigData
    {
        [JsonProperty("csn")]
        public string Csn { get; set; }

        [JsonProperty("visitorData")]
        public string VisitorData { get; set; }

        [JsonProperty("sessionIndex")]
        public long SessionIndex { get; set; }

        [JsonProperty("rootVisualElementType")]
        public long RootVisualElementType { get; set; }
    }

    public partial class Topbar
    {
        [JsonProperty("desktopTopbarRenderer")]
        public DesktopTopbarRenderer DesktopTopbarRenderer { get; set; }
    }

    public partial class DesktopTopbarRenderer
    {
        [JsonProperty("logo")]
        public Logo Logo { get; set; }

        [JsonProperty("searchbox")]
        public Searchbox Searchbox { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("countryCode")]
        public string CountryCode { get; set; }

        [JsonProperty("topbarButtons")]
        public List<TopbarButton> TopbarButtons { get; set; }

        [JsonProperty("hotkeyDialog")]
        public HotkeyDialog HotkeyDialog { get; set; }

        [JsonProperty("backButton")]
        public BackButtonClass BackButton { get; set; }

        [JsonProperty("forwardButton")]
        public BackButtonClass ForwardButton { get; set; }

        [JsonProperty("a11ySkipNavigationButton")]
        public A11YSkipNavigationButtonClass A11YSkipNavigationButton { get; set; }
    }

    public partial class A11YSkipNavigationButtonClass
    {
        [JsonProperty("buttonRenderer")]
        public A11YSkipNavigationButtonButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class A11YSkipNavigationButtonButtonRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("isDisabled")]
        public bool IsDisabled { get; set; }

        [JsonProperty("text")]
        public TitleClass Text { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("command", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public Command Command { get; set; }
    }

    public partial class Command
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public CommandCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public CommandSignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class CommandCommandMetadata
    {
        [JsonProperty("webCommandMetadata")]
        public TentacledWebCommandMetadata WebCommandMetadata { get; set; }
    }

    public partial class TentacledWebCommandMetadata
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("sendPost")]
        public bool SendPost { get; set; }
    }

    public partial class CommandSignalServiceEndpoint
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }

        [JsonProperty("actions")]
        public List<StickyAction> Actions { get; set; }
    }

    public partial class StickyAction
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("signalAction")]
        public Signal SignalAction { get; set; }
    }

    public partial class Signal
    {
        [JsonProperty("signal")]
        public string SignalSignal { get; set; }
    }

    public partial class BackButtonClass
    {
        [JsonProperty("buttonRenderer")]
        public BackButtonButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class BackButtonButtonRenderer
    {
        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("command")]
        public Command Command { get; set; }
    }

    public partial class HotkeyDialog
    {
        [JsonProperty("hotkeyDialogRenderer")]
        public HotkeyDialogRenderer HotkeyDialogRenderer { get; set; }
    }

    public partial class HotkeyDialogRenderer
    {
        [JsonProperty("title")]
        public TitleClass Title { get; set; }

        [JsonProperty("sections")]
        public List<HotkeyDialogRendererSection> Sections { get; set; }

        [JsonProperty("dismissButton")]
        public A11YSkipNavigationButtonClass DismissButton { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class HotkeyDialogRendererSection
    {
        [JsonProperty("hotkeyDialogSectionRenderer")]
        public HotkeyDialogSectionRenderer HotkeyDialogSectionRenderer { get; set; }
    }

    public partial class HotkeyDialogSectionRenderer
    {
        [JsonProperty("title")]
        public TitleClass Title { get; set; }

        [JsonProperty("options")]
        public List<Option> Options { get; set; }
    }

    public partial class Option
    {
        [JsonProperty("hotkeyDialogSectionOptionRenderer")]
        public HotkeyDialogSectionOptionRenderer HotkeyDialogSectionOptionRenderer { get; set; }
    }

    public partial class HotkeyDialogSectionOptionRenderer
    {
        [JsonProperty("label")]
        public TitleClass Label { get; set; }

        [JsonProperty("hotkey")]
        public string Hotkey { get; set; }

        [JsonProperty("hotkeyAccessibilityLabel", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public HotkeyAccessibilityLabelClass HotkeyAccessibilityLabel { get; set; }
    }

    public partial class Logo
    {
        [JsonProperty("topbarLogoRenderer")]
        public TopbarLogoRenderer TopbarLogoRenderer { get; set; }
    }

    public partial class TopbarLogoRenderer
    {
        [JsonProperty("iconImage")]
        public IconImage IconImage { get; set; }

        [JsonProperty("tooltipText")]
        public TitleClass TooltipText { get; set; }

        [JsonProperty("endpoint")]
        public EndpointClass Endpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class EndpointClass
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("browseEndpoint")]
        public EndpointBrowseEndpoint BrowseEndpoint { get; set; }
    }

    public partial class EndpointBrowseEndpoint
    {
        [JsonProperty("browseId")]
        public string BrowseId { get; set; }
    }

    public partial class Searchbox
    {
        [JsonProperty("fusionSearchboxRenderer")]
        public FusionSearchboxRenderer FusionSearchboxRenderer { get; set; }
    }

    public partial class FusionSearchboxRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("placeholderText")]
        public TitleClass PlaceholderText { get; set; }

        [JsonProperty("config")]
        public Config Config { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("searchEndpoint")]
        public FusionSearchboxRendererSearchEndpoint SearchEndpoint { get; set; }
    }

    public partial class Config
    {
        [JsonProperty("webSearchboxConfig")]
        public WebSearchboxConfig WebSearchboxConfig { get; set; }
    }

    public partial class WebSearchboxConfig
    {
        [JsonProperty("requestLanguage")]
        public string RequestLanguage { get; set; }

        [JsonProperty("requestDomain")]
        public string RequestDomain { get; set; }

        [JsonProperty("hasOnscreenKeyboard")]
        public bool HasOnscreenKeyboard { get; set; }

        [JsonProperty("focusSearchbox")]
        public bool FocusSearchbox { get; set; }
    }

    public partial class FusionSearchboxRendererSearchEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("searchEndpoint")]
        public PurpleSearchEndpoint SearchEndpoint { get; set; }
    }

    public partial class PurpleSearchEndpoint
    {
        [JsonProperty("query")]
        public string Query { get; set; }
    }

    public partial class TopbarButton
    {
        [JsonProperty("topbarMenuButtonRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public TopbarMenuButtonRenderer TopbarMenuButtonRenderer { get; set; }

        [JsonProperty("notificationTopbarButtonRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public NotificationTopbarButtonRenderer NotificationTopbarButtonRenderer { get; set; }
    }

    public partial class NotificationTopbarButtonRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("menuRequest")]
        public MenuRequest MenuRequest { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("accessibility")]
        public HotkeyAccessibilityLabelClass Accessibility { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("updateUnseenCountEndpoint")]
        public UpdateUnseenCountEndpoint UpdateUnseenCountEndpoint { get; set; }

        [JsonProperty("notificationCount")]
        public long NotificationCount { get; set; }

        [JsonProperty("handlerDatas")]
        public List<string> HandlerDatas { get; set; }
    }

    public partial class MenuRequest
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public MenuRequestSignalServiceEndpoint SignalServiceEndpoint { get; set; }
    }

    public partial class MenuRequestSignalServiceEndpoint
    {
        [JsonProperty("signal")]
        public string Signal { get; set; }

        [JsonProperty("actions")]
        public List<IndigoAction> Actions { get; set; }
    }

    public partial class IndigoAction
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("openPopupAction")]
        public OpenPopupAction OpenPopupAction { get; set; }
    }

    public partial class OpenPopupAction
    {
        [JsonProperty("popup")]
        public Popup Popup { get; set; }

        [JsonProperty("popupType")]
        public string PopupType { get; set; }

        [JsonProperty("beReused")]
        public bool BeReused { get; set; }
    }

    public partial class Popup
    {
        [JsonProperty("multiPageMenuRenderer")]
        public PopupMultiPageMenuRenderer MultiPageMenuRenderer { get; set; }
    }

    public partial class PopupMultiPageMenuRenderer
    {
        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("showLoadingSpinner")]
        public bool ShowLoadingSpinner { get; set; }
    }

    public partial class UpdateUnseenCountEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public ContinuationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("signalServiceEndpoint")]
        public Signal SignalServiceEndpoint { get; set; }
    }

    public partial class TopbarMenuButtonRenderer
    {
        [JsonProperty("icon", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public IconImage Icon { get; set; }

        [JsonProperty("menuRenderer", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public TopbarMenuButtonRendererMenuRenderer MenuRenderer { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("accessibility")]
        public HotkeyAccessibilityLabelClass Accessibility { get; set; }

        [JsonProperty("tooltip")]
        public string Tooltip { get; set; }

        [JsonProperty("style", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string Style { get; set; }

        [JsonProperty("targetId", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string TargetId { get; set; }

        [JsonProperty("avatar", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public Avatar Avatar { get; set; }

        [JsonProperty("menuRequest", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public MenuRequest MenuRequest { get; set; }
    }

    public partial class Avatar
    {
        [JsonProperty("thumbnails")]
        public List<ThumbnailElement> Thumbnails { get; set; }

        [JsonProperty("accessibility")]
        public HotkeyAccessibilityLabelClass Accessibility { get; set; }
    }

    public partial class TopbarMenuButtonRendererMenuRenderer
    {
        [JsonProperty("multiPageMenuRenderer")]
        public MenuRendererMultiPageMenuRenderer MultiPageMenuRenderer { get; set; }
    }

    public partial class MenuRendererMultiPageMenuRenderer
    {
        [JsonProperty("sections")]
        public List<MultiPageMenuRendererSection> Sections { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("style", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string Style { get; set; }
    }

    public partial class MultiPageMenuRendererSection
    {
        [JsonProperty("multiPageMenuSectionRenderer")]
        public MultiPageMenuSectionRenderer MultiPageMenuSectionRenderer { get; set; }
    }

    public partial class MultiPageMenuSectionRenderer
    {
        [JsonProperty("items")]
        public List<MultiPageMenuSectionRendererItem> Items { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class MultiPageMenuSectionRendererItem
    {
        [JsonProperty("compactLinkRenderer")]
        public CompactLinkRenderer CompactLinkRenderer { get; set; }
    }

    public partial class CompactLinkRenderer
    {
        [JsonProperty("icon")]
        public IconImage Icon { get; set; }

        [JsonProperty("title")]
        public TitleClass Title { get; set; }

        [JsonProperty("navigationEndpoint")]
        public CompactLinkRendererNavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("style", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string Style { get; set; }
    }

    public partial class CompactLinkRendererNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("commandMetadata")]
        public NavigationEndpointCommandMetadata CommandMetadata { get; set; }

        [JsonProperty("uploadEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public UploadEndpoint UploadEndpoint { get; set; }

        [JsonProperty("signalNavigationEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public Signal SignalNavigationEndpoint { get; set; }

        [JsonProperty("urlEndpoint", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public UrlEndpoint UrlEndpoint { get; set; }
    }

    public partial class UploadEndpoint
    {
        [JsonProperty("hack")]
        public bool Hack { get; set; }
    }

    public partial class UrlEndpoint
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("target")]
        public string Target { get; set; }
    }

    

   

   

   

   

  

       

   

   

   
}


